### Search
GET {{host}}/api/adm/v1/asset-external-provider/unsplash_cms/search/?term=fifa&limit=30
Content-Type: application/json
Authorization: Bearer {{adm_access_token}}

### Get by ids
GET {{host}}/api/adm/v1/asset-external-provider/unsplash_cms/ids/cjYQBSKDSII
Content-Type: application/json
Authorization: Bearer {{adm_access_token}}

### Get by id
GET {{host}}/api/adm/v1/asset-external-provider/unsplash_cms/cjYQBSKDSII
Content-Type: application/json
Authorization: Bearer {{adm_access_token}}

### POST by id
POST {{host}}/api/adm/v1/image/licence/1/external-provider
Content-Type: application/json
Authorization: Bearer {{adm_access_token}}

{
  "id": "N6zIsVM_dY8",
  "externalProvider": "unsplash_cms"
}
