### Login admin
GET {{host}}/force/login/adm/10001039
Accept: application/json
Content-Type: application/json

> {%
  client.global.set('adm_access_token', response.body.accessToken);
%}

### Refresh token admin
POST {{host}}/api/auth/refresh-token
Content-Type: application/json

### Logout admin
GET {{host}}/api/auth/logout?url={{host}}
Content-Type: application/json
