### Login admin
GET {{host}}/force/login/adm/10001039
Content-Type: application/json

{
  "username": "dam_admin@anzusystems.dev",
  "password": "admin"
}

### Get distributions by asset file
GET {{host}}/api/adm/v1/distribution/asset-file/aa967cf4-0ea9-499e-be2a-13bf0b63eabe
Content-Type: application/json

> {%
  client.global.set('assetId', response.body.data[0].assetId)
%}

### Get distributions by asset file
GET {{host}}/api/adm/v1/distribution/asset/{{assetId}}
Content-Type: application/json

### Get ext system configuration
GET {{host}}/api/adm/v1/configuration/ext-system/1
Content-Type: application/json

### Check if distribution is authorized
GET {{host}}/api/adm/v1/distribution/youtube_cms_main/authorized
Content-Type: application/json

### Get authorize URL
GET {{host}}/api/adm/v1/youtube-distribution/youtube_cms_main/auth-url
Content-Type: application/json

### Youtube playlists
GET http://core-dam.sme.localhost/api/adm/v1/youtube-distribution/youtube_cms_main/playlist
Content-Type: application/json

### Youtube languages
GET http://core-dam.sme.localhost/api/adm/v1/youtube-distribution/youtube_cms_main/language
Content-Type: application/json

### Ext system config
GET {{host}}/api/adm/v1/configuration/ext-system/1
Content-Type: application/json

### Youtube prepare distribution payload
GET {{host}}/api/adm/v1/youtube-distribution/asset-file/aa967cf4-0ea9-499e-be2a-13bf0b63eabe/prepare-payload/youtube_cms_main
Content-Type: application/json

### Youtube distribute
POST {{host}}/api/adm/v1/youtube-distribution/asset-file/aa967cf4-0ea9-499e-be2a-13bf0b63eabe/distribute
Content-Type: application/json

{
  "publishAt": null,
  "distributionService": "youtube_cms_main",
  "privacy": "private",
  "playlist": "",
  "language": "as",
  "texts": {
    "title": "title",
    "description": "description",
    "keywords": [
      "aaa",
      "bbb"
    ]
  },
  "flags": {
    "embeddable": true,
    "forKids": true,
    "notifySubscribers": true
  }
}

> {%
  client.global.set('youtubeId', response.body.id)
%}

### Youtube redistribute
PUT {{host}}/api/adm/v1/youtube-distribution/1eda8a3c-2f59-612a-9e41-65e77a866c4e/redistribute
Content-Type: application/json

{
  "publishAt": null,
  "distributionService": "youtube_cms_main",
  "privacy": "private",
  "playlist": "",
  "language": "as",
  "texts": {
    "title": "title",
    "description": "description",
    "keywords": [
      "aaa",
      "bbb"
    ]
  },
  "flags": {
    "embeddable": true,
    "forKids": true,
    "notifySubscribers": true
  }
}

> {%
    client.global.set('youtubeId', response.body.id)
%}

### Jw prepare distribution payload
GET {{host}}/api/adm/v1/jw-distribution/asset-file/aa967cf4-0ea9-499e-be2a-13bf0b63eabe/prepare-payload/jw_cms
Content-Type: application/json

### Jw distribute
POST {{host}}/api/adm/v1/jw-distribution/asset-file/aa967cf4-0ea9-499e-be2a-13bf0b63eabe/distribute
Content-Type: application/json

{
  "texts": {
    "title": "Video title",
    "description": "Custom video description",
    "author": "Aarne Ormonde",
    "keywords": [
      "News",
      "Podcast",
      "Politics"
    ]
  },
  "distributionService": "jw_cms",
  "publishAt": "2023-02-24T11:53:13.000000Z"
}

> {%
  client.global.set('jwId', response.body.id);
%}

### Jw redistribute
PUT {{host}}/api/adm/v1/jw-distribution/1eda8a1e-2780-6d9a-a70c-cb28974b9ab6/redistribute
Content-Type: application/json

{
  "texts": {
    "title": "Video title updated",
    "description": "Custom video description",
    "author": "Aarne Ormonde",
    "keywords": [
      "News",
      "Podcast",
      "Politics"
    ]
  },
  "distributionService": "jw_cms"
}

> {%
    client.global.set('jwId', response.body.id)
%}

### Custom distribution custom form
GET {{host}}/api/adm/v1/asset-custom-form/distribution-service/artemis_cms/element
Content-Type: application/json

### Custom distribute
POST {{host}}/api/adm/v1/custom-distribution/asset-file/aa967cf4-0ea9-499e-be2a-13bf0b63eabe/distribute
Content-Type: application/json

{
  "distributionService": "artemis_cms",
  "customData": {
    "createArticle": true
  },
  "blockedBy": ["{{youtubeId}}", "{{jwId}}"]
}

> {%
  client.global.set('customId', response.body.id)
%}

### Get asset files
GET {{host}}/api/adm/v1/distribution/asset-file/aa967cf4-0ea9-499e-be2a-13bf0b63eabe
Content-Type: application/json

### Get distribution
GET {{host}}/api/adm/v1/distribution/1ed71b91-167c-66ec-84e8-0389a2aa1cbc
Content-Type: application/json
