### Create assest with associated image file
POST {{host}}/api/adm/v1/image/licence/1
Content-Type: application/json

{
  "mimeType": "image/jpe",
  "checksum": "123456",
  "size": 323386
}

> {%
  client.global.set('imageId', response.body.id)
  client.global.set('assetId', response.body.asset)
%}

### Upload chunk 1
POST {{host}}/api/adm/v1/image/{{imageId}}/chunk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="filename.jpg"

< ../../tests/data/chunk/chunkaa

--boundary
Content-Disposition: form-data; name="chunk";
Content-Type: application/json

{
  "offset": 0,
  "size": 262144
}

### Upload chunk 2
POST {{host}}/api/adm/v1/image/{{imageId}}/chunk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="filename.jpg"

< ../../tests/data/chunk/chunkab

--boundary
Content-Disposition: form-data; name="chunk";
Content-Type: application/json

{
  "offset": 262144,
  "size": 61242
}

### Finish upload
PATCH {{host}}/api/adm/v1/image/{{imageId}}/uploaded
Content-Type: application/json

  {
    "checksum": "123456"
  }


### deleteImage
DELETE {{host}}/api/adm/v1/asset/{{assetId}}
