### Create assest with associated image file
POST {{host}}/api/adm/v1/image/licence/1
Content-Type: application/json

{
  "mimeType": "image/jpeg",
  "checksum": "123456"
}

> {%
  client.global.set('imageId', response.body.id)
  client.global.set('assetId', response.body.asset)
%}

### Upload chunk 1
POST {{host}}/api/adm/v1/image/{{imageId}}/chunk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="filename.jpg"

< ../../tests/data/chunk/chunkaa

--boundary
Content-Disposition: form-data; name="chunk";
Content-Type: application/json

{
  "offset": 0,
  "size": 262144
}

### Upload chunk 2
POST {{host}}/api/adm/v1/image/{{imageId}}/chunk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="filename.jpg"

< ../../tests/data/chunk/chunkab

--boundary
Content-Disposition: form-data; name="chunk";
Content-Type: application/json

{
  "offset": 262144,
  "size": 61242
}

### Finish upload
PATCH {{host}}/api/adm/v1/image/{{imageId}}/uploaded
Content-Type: application/json

### Preview image
GET {{host}}/image/w500-h500-c0/{{imageId}}

### Bulk update
PATCH {{host}}/api/adm/v1/asset/bulk-update
Content-Type: application/json

[
  {
    "id": "{{assetId}}",
    "title": "Title",
    "description": "Descr",
    "described": true
  }
]

### Bulk update
