### Create assest with associated image file
POST {{host}}/api/adm/v1/image/licence/100000
Content-Type: application/json

{
  "mimeType": "image/jpeg",
  "checksum": "123456",
  "size": 323386
}

> {%
  client.global.set('imageId', response.body.id)
  client.global.set('assetId', response.body.asset)
%}

### Change flags
PATCH {{host}}/api/adm/v1/image/copy-to-licence
Content-Type: application/json
Authorization: Bearer {{adm_access_token}}

[
  {
    "asset": "1ef8da0b-70dd-6208-bd5a-1d258b33b908",
    "targetAssetLicence": 100001
  },
  {
    "asset": "1ef8d8b2-5f14-6ad0-94b3-df1133af20b1",
    "targetAssetLicence": 100001
  },
  {
    "asset": "1ef8d872-813a-6942-a31f-576bc4462ec8",
    "targetAssetLicence": 100001
  },
  {
    "asset": "1ef8d836-abba-6bd6-b93e-87046159e1f0",
    "targetAssetLicence": 100001
  }
]

### Rotate
PATCH {{host}}/api/adm/v1/image/892d7b56-7423-4428-86a0-2d366685d823/rotate/90
Content-Type: application/json

### Change flags
PUT {{host}}/api/adm/v1/image/892d7b56-7423-4428-86a0-2d366685d823
Content-Type: application/json

{
  "flags": {
    "public": false,
    "singleUse": false
  }
}

### Upload chunk 1
POST {{host}}/api/adm/v1/image/{{imageId}}/chunk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="filename.jpg"

< ../../tests/data/chunk/chunkaa

--boundary
Content-Disposition: form-data; name="chunk";
Content-Type: application/json

{
  "offset": 0,
  "size": 262144
}

### Upload chunk 2
POST {{host}}/api/adm/v1/image/{{imageId}}/chunk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="filename.jpg"

< ../../tests/data/chunk/chunkab

--boundary
Content-Disposition: form-data; name="chunk";
Content-Type: application/json

{
  "offset": 262144,
  "size": 61242
}

### Finish upload
PATCH {{host}}/api/adm/v1/image/{{imageId}}/uploaded
Content-Type: application/json

  {
    "checksum": "123456"
  }


### deleteImage
DELETE {{host}}/api/adm/v1/asset/{{assetId}}
