### Login admin
POST {{host}}/force/login/10001039
Content-Type: application/json

{
  "username": "dam_admin@anzusystems.dev",
  "password": "admin"
}

### Set podcast image preview
PUT {{host}}/api/adm/v1/podcast/8fe7196e-1480-41b6-b0b3-1c73c79f3452
Content-Type: application/json

{
  "id": "8fe7196e-1480-41b6-b0b3-1c73c79f3452",
  "licence": 100000,
  "texts": {
    "title": "Text"
  },
  "imagePreview": {
    "imageFile": "0d584443-2718-470a-b9b1-92d2d9c7447c",
    "position": 0
  }
}

### GET FIRST EPISODE
GET {{host}}/api/adm/v1/podcast-episode/podcast/8fe7196e-1480-41b6-b0b3-1c73c79f3452
Content-Type: application/json

> {%
    client.global.set('episodeId', response.body.data[0].id)
%}

### Set podcast-episode image preview
PUT {{host}}/api/adm/v1/podcast-episode/{{episodeId}}
Content-Type: application/json

{
  "id": "{{episodeId}}",
  "podcast": "8fe7196e-1480-41b6-b0b3-1c73c79f3452",
  "texts": {
    "title": "Text"
  },
    "imagePreview": {
    "imageFile": "0d584443-2718-470a-b9b1-92d2d9c7447c",
    "position": 0
  }
}

### Set podcast-episode image preview
PUT {{host}}/api/adm/v1/podcast-episode/{{episodeId}}
Content-Type: application/json

{
  "id": "{{episodeId}}",
  "podcast": "8fe7196e-1480-41b6-b0b3-1c73c79f3452",
  "texts": {
    "title": "Text"
  },
    "imagePreview": {
    "imageFile": "0d584443-2718-470a-b9b1-92d2d9c7447c",
    "position": 0
  }
}

### Update VideoFile image preview
PUT {{host}}/api/adm/v1/video/aa967cf4-0ea9-499e-be2a-13bf0b63eabe
Content-Type: application/json

{
  "id": "aa967cf4-0ea9-499e-be2a-13bf0b63eabe",
  "imagePreview": {
    "imageFile": "0d584443-2718-470a-b9b1-92d2d9c7447c",
    "position": 0
  }
}

### Update VideoFile image preview
PUT {{host}}/api/adm/v1/video/aa967cf4-0ea9-499e-be2a-13bf0b63eabe
Content-Type: application/json

{
  "id": "aa967cf4-0ea9-499e-be2a-13bf0b63eabe",
  "imagePreview": null
}

### Get distribution previews
GET {{host}}/api/adm/v1/video/aa967cf4-0ea9-499e-be2a-13bf0b63eabe/distribution-preview
Content-Type: application/json

### Set VideoFile image preview from distribution
PATCH {{host}}/api/adm/v1/video/aa967cf4-0ea9-499e-be2a-13bf0b63eabe/distribution-preview/1eda6eea-3f9c-6f18-b9ea-5dd60c895846
Content-Type: application/json
