anzu_systems_common:
  permissions:
    roles: [ ROLE_USER, ROLE_UGC, ROLE_ADMIN, ROLE_DAM_ADMIN, ROLE_SYS_API, ROLE_SYS_JOB_API ]
    config:
      dam_asset:
        create:
        update:
        view:
        delete:
      dam_video:
        create:
        update:
        view:
        delete:
      dam_audio:
        create:
        update:
        view:
        delete:
      dam_document:
        create:
        update:
        view:
        delete:
      dam_image:
        create:
        update:
        view:
        delete:
      dam_assetCustomForm:
        create:
        update:
        view:
      dam_customFormElement:
        view:
      dam_regionOfInterest:
        create:
        update:
        view:
        delete:
      dam_extSystem:
        update:
        view:
        list:
        ui:
      dam_assetLicence:
        create:
        update:
        list:
        view:
        ui:
      dam_author:
        create:
        update:
        view:
        delete:
        ui:
      dam_keyword:
        create:
        update:
        view:
        delete:
        ui:
      dam_podcast:
        create:
        update:
        view:
        delete:
        ui:
      dam_podcastEpisode:
        create:
        update:
        view:
        delete:
        ui:
      dam_distributionCategory:
        create:
        update:
        view:
        delete:
        ui:
      dam_distributionCategorySelect:
        update:
        view:
        ui:
      dam_distribution:
        access:
      dam_assetExternalProvider:
        access:
      dam_user:
        create:
        update:
        view:
        ugcImpersonate:
        ui:
      dam_permissionGroup:
        create:
        update:
        view:
        delete:
        ui:
      dam_videoShow:
        create:
        update:
        view:
        delete:
        ui:
      dam_videoShowEpisode:
        create:
        update:
        view:
        delete:
        ui:
      dam_log:
        ui:
      dam_job:
        view:
        create:
        delete:
        ui:
    translation:
      roles:
        ROLE_USER:
          en: User
          sk: Používateľ
        ROLE_ADMIN:
          en: Super Admin
          sk: Super Administrátor
        ROLE_DAM_ADMIN:
          en: DAM Admin
          sk: DAM Administrátor
        ROLE_UGC:
          sk: UGC Používateľ
          en: UGC User
        ROLE_SYS_API:
          en: System Api
          sk: Systémové Api
        ROLE_SYS_JOB_API:
          en: System Job Api
          sk: Systémové Joby Api
      actions:
        ui:
          en: UI
          sk: UI
        view:
          en: View
          sk: Zobraz
        update:
          en: Update
          sk: Uprav
        create:
          en: Create
          sk: Vytvor
        delete:
          en: Delete
          sk: Zmaž
        list:
          en: List
          sk: List
        access:
          en: Access
          sk: Prístup
        ugcImpersonate:
          en: UGC Impersonate
          sk: UGC Impersonaluj
      subjects:
        dam_asset:
          en: Asset
          sk: Asset
        dam_video:
          en: Video
          sk: Video
        dam_audio:
          en: Audio
          sk: Audio
        dam_document:
          en: Document
          sk: Dokument
        dam_image:
          en: Image
          sk: Obrázok
        dam_assetCustomForm:
          en: Custom Form
          sk: Vlastné polia
        dam_customFormElement:
          en: Custom Form Element
          sk: Vlastné polia element
        dam_regionOfInterest:
          en: Region of Interest
          sk: Región záujmu
        dam_extSystem:
          en: External system
          sk: Externý systém
        dam_assetLicence:
          en: Asset Licence
          sk: Asset Licencia
        dam_author:
          en: Author
          sk: Autor
        dam_keyword:
          en: Keyword
          sk: Kľúčové slovo
        dam_podcast:
          en: Podcast
          sk: Podcast
        dam_podcastEpisode:
          en: Podcast Episode
          sk: Podcastová epizóda
        dam_videoShow:
          en: Video relácia
          sk: Video show
        dam_videoShowEpisode:
          en: Video relácia (epizóda)
          sk: Video show (episode)
        dam_distributionCategory:
          en: Distribution Category
          sk: Distribučná kategória
        dam_distributionCategorySelect:
          en: Distribution Category Select
          sk: Distribučná kategória selekt
        dam_distribution:
          en: Distribution
          sk: Distribúcia
        dam_assetExternalProvider:
          en: Asset External Provider
          sk: Asset externý provider
        dam_user:
          en: User
          sk: Používateľ
        dam_permissionGroup:
          en: Group permission
          sk: Skupinové povolenie
        dam_log:
          en: Log
          sk: Log
        dam_job:
          en: Job
          sk: Job
