anzu_systems_core_dam:
  ext_systems:
    cms:
      id: 1
      asset_external_providers:
        unsplash_cms:
          title: Unsplash
          import_author_id: 0185f3e8-7f5e-750e-9075-29cdd412b988
      image:
        enabled: true
        title: ['customData:title']
        custom_metadata_pinned_amount: 3
        storage_name: 'cms.image'
        crop_storage_name: 'cms.crop'
        chunk_storage_name: 'cms.image'
        size_limit: '%env(byte_size:APP_CMS_IMAGE_MAX_SIZE)%'
        public_domain: public_image
        admin_domain: admin_image
        roi_width: 16
        roi_height: 9
        file_slots:
          default: default
          slots: [ default ]
        keywords:
          enabled: true
          required: false
          autocomplete_from_exif_metadata_tags:
            Keywords: ','
            Subjects: ','
        authors:
          enabled: true
          required: false
          autocomplete_from_exif_metadata_tags:
            Artist: ','
            Owners: ','
            OwnerName: ~
        asset_external_providers_map:
          title:
            source_property_path: 'texts.displayTitle'
            destination_property_path: 'metadata.customData[title]'
          description:
            source_property_path: 'texts.description'
            destination_property_path: 'metadata.customData[description]'
            normalizers:
              - { type: string, options: { length: 5000 } }
      audio:
        enabled: true
        keywords:
          enabled: true
          required: false
          autocomplete_from_exif_metadata_tags:
            Keywords: ','
            Subjects: ','
        authors:
          enabled: true
          required: false
          autocomplete_from_exif_metadata_tags:
            Artist: ','
            Owners: ','
            OwnerName: ~
        title: ['customData:title']
        custom_metadata_pinned_amount: 3
        public_domain_name: '%env(resolve:string:DOMAIN_PUBLIC_AUDIO)%'
        storage_name: 'cms.audio'
        public_storage: 'cms.public_audio'
        chunk_storage_name: 'cms.audio'
        size_limit: '%env(byte_size:APP_CMS_AUDIO_MAX_SIZE)%'
        distribution:
          distribution_services: [ artemis_podcast_cms ]
          distribution_requirements:
            artemis_podcast_cms:
              title: 'Artemis Podcasty'
              blocked_by: [ ]
              strategy: none
              distribution_metadata_map:
                title:
                  source_property_path: 'metadata.customData[title]'
                  destination_property_path: 'texts.title'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                description:
                  source_property_path: 'metadata.customData[description]'
                  destination_property_path: 'texts.description'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                keywords:
                  source_property_path: 'keywords_as_string_array'
                  destination_property_path: 'texts.keywords'
                authors:
                  source_property_path: 'authors_as_string_array'
                  destination_property_path: 'texts.authors'
              category_select:
                enabled: true
                required: true
        file_slots:
          default: free
          slots: [ free, premium, bonus ]
        podcast_episode_rss_map:
          title:
            source_property_path: 'title'
            destination_property_path: 'metadata.customData[title]'
            normalizers:
              - { type: string, options: { length: 64, empty_string: true } }
              - { type: html, options: { words_wrap: 0 } }
          description:
            source_property_path: 'description'
            destination_property_path: 'metadata.customData[description]'
            normalizers:
              - { type: string, options: { length: 5000, empty_string: true } }
              - { type: html, options: { words_wrap: 0 } }
        podcast_episode_entity_map:
          title:
            source_property_path: 'metadata.customData[title]'
            destination_property_path: 'texts.title'
            normalizers:
              - { type: string, options: { empty_string: true } }
          description:
            source_property_path: 'metadata.customData[description]'
            destination_property_path: 'texts.description'
            normalizers:
              - { type: string, options: { empty_string: true } }
      video:
        enabled: true
        keywords:
          enabled: true
          required: false
          autocomplete_from_exif_metadata_tags:
            Keywords: ','
            Subjects: ','
        authors:
          enabled: true
          required: false
          autocomplete_from_exif_metadata_tags:
            Artist: ','
            Owners: ','
            OwnerName: ~
        title: ['customData:title']
        video_episode_entity_map:
          title:
            source_property_path: 'metadata.customData[title]'
            destination_property_path: 'texts.title'
            normalizers:
              - { type: string, options: { empty_string: true } }
        custom_metadata_pinned_amount: 3
        storage_name: 'cms.video'
        chunk_storage_name: 'cms.video'
        size_limit: '%env(byte_size:APP_CMS_VIDEO_MAX_SIZE)%'
        file_slots: ~
        distribution:
          distribution_services: [ youtube_cms_main, youtube_cms_fici, jw_cms, artemis_video_cms ]
          distribution_requirements:
            youtube_cms_main:
              title: 'YouTube CMS'
              blocked_by: []
              strategy: none
              distribution_metadata_map:
                title:
                  source_property_path: 'metadata.customData[title]'
                  destination_property_path: 'texts.title'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                description:
                  source_property_path: 'metadata.customData[description]'
                  destination_property_path: 'texts.description'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                keywords:
                  source_property_path: 'keywords_as_string_array'
                  destination_property_path: 'texts.keywords'
              category_select:
                enabled: true
                required: false
            youtube_cms_fici:
              title: 'YouTube Fičí'
              distribution_metadata_map:
                title:
                  source_property_path: 'metadata.customData[title]'
                  destination_property_path: 'texts.title'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                description:
                  source_property_path: 'metadata.customData[description]'
                  destination_property_path: 'texts.description'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                keywords:
                  source_property_path: 'keywords_as_string_array'
                  destination_property_path: 'texts.keywords'
              blocked_by: [ ]
              strategy: none
            jw_cms:
              title: 'JW Player Video'
              distribution_metadata_map:
                title:
                  source_property_path: 'metadata.customData[title]'
                  destination_property_path: 'texts.title'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                description:
                  source_property_path: 'metadata.customData[description]'
                  destination_property_path: 'texts.description'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                keywords:
                  source_property_path: 'keywords_as_string_array'
                  destination_property_path: 'texts.keywords'
                author:
                  source_property_path: 'authors_as_string_array[0]'
                  destination_property_path: 'texts.null_author'
              blocked_by: [ ]
              strategy: none
              category_select:
                enabled: true
                required: false
            artemis_video_cms:
              title: 'Artemis'
              blocked_by: [youtube_cms_main, youtube_cms_fici, jw_cms]
              strategy: at_least_one # none, one_from_type, wait_for_all
              distribution_metadata_map:
                title:
                  source_property_path: 'metadata.customData[title]'
                  destination_property_path: 'texts.title'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                description:
                  source_property_path: 'metadata.customData[description]'
                  destination_property_path: 'texts.description'
                  normalizers:
                    - { type: string, options: { empty_string: true } }
                keywords:
                  source_property_path: 'keywords_as_string_array'
                  destination_property_path: 'texts.keywords'
                authors:
                  source_property_path: 'authors_as_string_array'
                  destination_property_path: 'texts.authors'
              category_select:
                enabled: true
                required: true
      document:
        enabled: true
        title: ['customData:title']
        custom_metadata_pinned_amount: 3
        storage_name: 'cms.document'
        chunk_storage_name: 'cms.document'
        size_limit: '%env(byte_size:APP_CMS_DOCUMENT_MAX_SIZE)%'
        file_slots: ~
    blog:
      id: 4
      image:
        enabled: true
        public_domain: public_image
        admin_domain: admin_image
        title: ['customData:title']
        custom_metadata_pinned_amount: 2
        storage_name: 'blog.image'
        crop_storage_name: 'blog.crop'
        chunk_storage_name: 'blog.chunk'
        size_limit: '%env(byte_size:APP_CMS_BLOG_MAX_SIZE)%'
        roi_width: 16
        roi_height: 9
        file_slots:
          default: default
          slots: [ default ]
    tools:
      id: 4
      image:
        enabled: true
        public_domain: public_image
        admin_domain: admin_image
        title: [ 'customData:title' ]
        custom_metadata_pinned_amount: 2
        storage_name: 'cms.image'
        crop_storage_name: 'cms.crop'
        chunk_storage_name: 'cms.chunk'
        size_limit: '%env(byte_size:APP_CMS_IMAGE_MAX_SIZE)%'
        roi_width: 16
        roi_height: 9
        file_slots:
          default: default
          slots: [ default ]
  domains:
    admin_image:
      domain: '%env(resolve:string:DOMAIN_ADMIN_IMAGE)%'
      max_age: '%env(int:DOMAIN_ADMIN_IMAGE_MAX_AGE)%'
      cache_ttl: '%env(int:DOMAIN_ADMIN_IMAGE_CACHE_TTL)%'
      public: '%env(bool:DOMAIN_ADMIN_IMAGE_PUBLIC)%'
    public_image:
      domain: '%env(resolve:string:DOMAIN_PUBLIC_IMAGE)%'
      max_age: '%env(int:DOMAIN_PUBLIC_IMAGE_MAX_AGE)%'
      cache_ttl: '%env(int:DOMAIN_PUBLIC_IMAGE_CACHE_TTL)%'
      public: '%env(bool:DOMAIN_PUBLIC_IMAGE_PUBLIC)%'
    public_audio:
      domain: '%env(resolve:string:DOMAIN_PUBLIC_AUDIO)%'
      max_age: 0
      cache_ttl: 60
      public: false
