anzu_systems_core_dam:
  settings:
    default_ext_system_id: 1
    default_asset_licence_id: 1
    allow_select_ext_system: false
    allow_select_licence: false
    admin_allow_list_name: 'admin'
    max_bulk_item_count: 10
    acl_check_enabled: true
    image_chunk_config:
      min_size: 200000
      max_size: 500000000
  display_title:
    image:
      - 'customData:title'
      - 'customData:headline'
      - 'assetTexts:title'
      - 'assetFileAttributes:originFileName'
      - 'asset:id'
      - 'assetFile:id'
      - 'assetTexts:title'
    audio:
      - 'customData:title'
      - 'customData:headline'
      - 'assetTexts:title'
      - 'assetFileAttributes:originFileName'
      - 'asset:id'
      - 'assetFile:id'
      - 'assetTexts:title'
    video:
      - 'customData:title'
      - 'customData:headline'
      - 'assetTexts:title'
      - 'assetFileAttributes:originFileName'
      - 'asset:id'
      - 'assetFile:id'
      - 'assetTexts:title'
    document:
      - 'customData:title'
      - 'customData:headline'
      - 'assetTexts:title'
      - 'assetFileAttributes:originFileName'
      - 'asset:id'
      - 'assetFile:id'
      - 'assetTexts:title'
  file_operations:
    tmp_dir_path: '/tmp'
    fixtures_dir_path: '%kernel.project_dir%/var/mnt/data/fixtures'
  exif_metadata:
    common_metadata:
      Software:
        autoFillField: 'title'
      ExifVersion:
        autoFillField: 'title'
      Make: ~
      Artist: ~
      Description: ~
      Rights: ~
      Title: ~
      Subject: ~
      Headline: ~
      City: ~
      Credit: ~
      Source: ~
      State: ~
      Creator: ~
      Country: ~
      DateCreated: ~
      Keywords: ~
      OwnerName: ~
    image_metadata:
      ColorSpace:
        autoFillField: 'description'
      Flash: ~
      ImageDescription: ~
  image_settings:
    optimal_resizes: [ 2000, 1000, 500, 100 ]
    enable_crop_cache: true  # todo implement
    color_set:
      red:
        rgb: [238, 2, 2]
      yellow:
        rgb: [251, 239, 0]
      blue:
        rgb: [30, 21, 246]
      orange:
        rgb: [244, 114, 0]
      green:
        rgb: [46, 145, 2]
      purple:
        rgb: [158, 11, 246]
      white:
        rgb: [255, 255, 255]
      black:
        rgb: [0, 0, 0]
      pink:
        rgb: [210, 7, 151]
      brown:
        rgb: [154, 0, 5]
    crop_allow_list:
      admin:
        domains: [ admin ]
        quality_whitelist: [ ]
        crops:
          # todo enum constant
#          - { width: 1920, height: 1080, tags: ['detail'] } # admin article large photo
          - { width: 500, height: 281, tags: ['roi_example'] }     # admin article small preview
#          - { width: 160, height: 90, tags: ['list'] }      # admin article gallery
          - { width: 0, height: 200, tags: ['list', 'roi_example'] }       # admin DAM listing
#          - { width: 0, height: 600, tags: ['list'] }       # admin DAM listing image detail
          - { width: 1920, height: 0, tags: ['detail'] }    # admin DAM image crop
      web_cms:
        domains: [ web_cms ]
        quality_whitelist: [ 90 ]
        crops:
          - { width: 800, height: 450 }   # anzu web general
          - { width: 350, height: 197 }   # anzu web box item photo
  storage:
    video: 'cms.audio'
    image: 'cms.image'
    document: 'cms.document'
    audio: 'cms.audio'
    chunk: 'cms.chunk'
    crop: 'cms.crop'
  ext_systems:
    cms:
      id: 1
      image:
        storage_name: 'cms.image'
        size_limit: 104857600 # 100MB
        roi_width: 16
        roi_height: 9
        file_versions:
          default: default
          versions: [ default ]
        keywords:
          enabled: true
          required: true
          autocomplete_from_exif_metadata_tags:
            Keywords: ','
            Subjects: ','
        authors:
          enabled: true
          required: true
          autocomplete_from_exif_metadata_tags:
            Owners: ','
            OwnerName: ~
      audio:
        storage_name: 'cms.audio'
        size_limit: 104857600 # 100MB
        file_versions:
          default: free
          versions: [ free, paid ]
      video:
        storage_name: 'cms.video'
        size_limit: 5242880000  # 5GB
        file_versions: ~
      document:
        storage_name: 'cms.document'
        size_limit: 1048576000 # 1GB
        file_versions: ~
    blog:
      id: 2
      image:
        storage_name: 'cms.image'
        size_limit: 104857600 # 100MB
        roi_width: 16
        roi_height: 9
        file_versions:
          default: default
          versions: [ default ]
  domains:
    admin:
      domain: '%env(resolve:string:DOMAIN_ADMIN_WEB)%'
    web_cms:
      domain: '%env(resolve:string:DOMAIN_CMS_WEB)%'
