core_dam:
  rtmp:
    storage_name: 'cms.rtmp'
    licence_id: 100000
    keyword_id: '1ee0b4fa-f21d-6794-8abb-153fe932206a'
    title_template: 'Live záznam z %s'
  artemis_audio_distribution:
    audio_free_slot_name: 'free'
    audio_premium_slot_name: 'premium'
    audio_bonus_slot_name: 'bonus'
    rss_jw_distribute: '%env(bool:RSS_JW_DISTRIBUTE)%'
    default_rubric_id: 6978
    custom_data_to_distribution_map:
      title:
        source_property_path: 'texts.title'
        destination_property_path: 'customData[title]'
        normalizers:
          - { type: string, options: { empty_string: true } }
      description:
        source_property_path: 'texts.description'
        destination_property_path: 'customData[description]'
        normalizers:
          - { type: string, options: { empty_string: true } }
      keywords:
        source_property_path: 'texts.keywords'
        destination_property_path: 'customData[keywords]'
      authors:
        source_property_path: 'texts.authors'
        destination_property_path: 'customData[authors]'
      free_url:
        source_property_path: 'texts.freeUrl'
        destination_property_path: 'customData[freeUrl]'
      premium_url:
        source_property_path: 'texts.premiumUrl'
        destination_property_path: 'customData[premiumUrl]'
      create_article:
        source_property_path: 'flags.createArticle'
        destination_property_path: 'customData[createArticle]'
      bonus_episode:
        source_property_path: 'flags.bonusEpisode'
        destination_property_path: 'customData[bonusEpisode]'
      ext_rss_id:
        source_property_path: 'texts.extRssId'
        destination_property_path: 'customData[extRssId]'
      rubric_id:
        source_property_path: 'texts.rubricId'
        destination_property_path: 'customData[rubricId]'
      episode_id:
        source_property_path: 'texts.episodeId'
        destination_property_path: 'customData[episodeId]'
      podcast_id:
        source_property_path: 'texts.podcastId'
        destination_property_path: 'customData[podcastId]'
      duration:
        source_property_path: 'attributes.duration'
        destination_property_path: 'customData[duration]'
      premium_duration:
        source_property_path: 'attributes.premiumDuration'
        destination_property_path: 'customData[premiumDuration]'
  artemis_video_distribution:
    default_rubric_id: 7026
    custom_data_to_distribution_map:
      title:
        source_property_path: 'texts.title'
        destination_property_path: 'customData[title]'
        normalizers:
          - { type: string, options: { empty_string: true } }
      description:
        source_property_path: 'texts.description'
        destination_property_path: 'customData[description]'
        normalizers:
          - { type: string, options: { empty_string: true } }
      keywords:
        source_property_path: 'texts.keywords'
        destination_property_path: 'customData[keywords]'
      authors:
        source_property_path: 'texts.authors'
        destination_property_path: 'customData[authors]'
      create_article:
        source_property_path: 'flags.createArticle'
        destination_property_path: 'customData[createArticle]'
      rubric_id:
        source_property_path: 'texts.rubricId'
        destination_property_path: 'customData[rubricId]'
