anzu_systems_core_dam:
    distribution_services:
        youtube_cms_main:
            type: youtubeDistribution
            title: Youtube CMS
            module: AnzuSystems\CoreDamBundle\Distribution\Modules\YoutubeDistributionModule
            auth_redirect_url: '%env(resolve:string:DISTRIBUTION_YOUTUBE_CMS_MAIN_REDIRECT_URL)%'
            required_auth: true
            options:
                oauth_credentials: '%env(resolve:string:DISTRIBUTION_YOUTUBE_CMS_MAIN_OAUTH_CREDENTIALS)%'
                channel_id: '%env(resolve:string:DISTRIBUTION_YOUTUBE_CMS_MAIN_CHANNEL_ID)%'
                region_code: 'SK'
        youtube_cms_fici:
            type: youtubeDistribution
            title: Youtube Fičí
            module: AnzuSystems\CoreDamBundle\Distribution\Modules\YoutubeDistributionModule
            auth_redirect_url: '%env(resolve:string:DISTRIBUTION_YOUTUBE_CMS_FICI_REDIRECT_URL)%'
            required_auth: true
            options:
                oauth_credentials: '%env(resolve:string:DISTRIBUTION_YOUTUBE_CMS_FICI_OAUTH_CREDENTIALS)%'
                channel_id: '%env(resolve:string:DISTRIBUTION_YOUTUBE_CMS_FICI_CHANNEL_ID)%'
                region_code: 'SK'
        jw_cms:
            type: jwDistribution
            title: JwVideo
            module: AnzuSystems\CoreDamBundle\Distribution\Modules\JwPlayerDistributionModule
            options:
                secret_v2: '%env(string:DISTRIBUTION_JW_CMS_SECRET_V2)%'
                site_id: '%env(string:DISTRIBUTION_JW_CMS_SITE_ID)%'
        artemis_cms:
            type: artemisDistribution
            title: Artemis CMS
            module: App\Distribution\Modules\ArtemisVideoDistributionModule
            options:
                endpoint: '%env(string:DISTRIBUTION_ARTEMIS_CMS_ENDPOINT)%'
                api_token: '%env(string:DISTRIBUTION_ARTEMIS_CMS_API_TOKEN)%'
                api_key_path: '%env(string:DISTRIBUTION_ARTEMIS_CMS_API_KEY_PATH)%'
                api_cert_path: '%env(string:DISTRIBUTION_ARTEMIS_CMS_API_CERT_PATH)%'
        custom_cms:
            type: customDistribution
            title: Custom CMS
            module: App\Distribution\Modules\ArtemisVideoDistributionModule
            options:
                endpoint: '%env(string:DISTRIBUTION_ARTEMIS_CMS_ENDPOINT)%'
                api_token: '%env(string:DISTRIBUTION_ARTEMIS_CMS_API_TOKEN)%'
                api_key_path: '%env(string:DISTRIBUTION_ARTEMIS_CMS_API_KEY_PATH)%'
                api_cert_path: '%env(string:DISTRIBUTION_ARTEMIS_CMS_API_CERT_PATH)%'

