doctrine_migrations:
    storage:
        table_storage:
            table_name: '_doctrine_migration_versions'
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'
    enable_profiler: '%kernel.debug%'
