jms_serializer:
    handlers:
        datetime:
            default_format: '%serializer_date_format%'
            default_timezone: "UTC"
        array_collection:
            initialize_excluded: false

    subscribers:
        doctrine_proxy:
            initialize_virtual_types: false
            initialize_excluded: false

    object_constructors:
        doctrine:
            fallback_strategy: "null"

    property_naming:
        id: jms_serializer.identical_property_naming_strategy

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: false
        infer_types_from_doctrine_metadata: false
        warmup:
            paths:
                included: ['%kernel.project_dir%/src/Entity']
                excluded: ['%kernel.project_dir%/src/Entity/Interfaces']

    expression_evaluator:
        id: jms_serializer.expression_evaluator

    default_context:
        serialization:
            serialize_null: true
            version: ~
            attributes: {}
            groups: ['Default']
            enable_max_depth_checks: false
        deserialization:
            serialize_null: true
            version: ~
            attributes: {}
            groups: ['Default']
            enable_max_depth_checks: false

    visitors:
        json_serialization:
            options:
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JMS\Serializer\Serializer: '@jms_serializer'
