framework:
    messenger:
        transports: ~
        buses:
            messenger.bus.default:
                middleware:
                    AnzuSystems\CommonBundle\Messenger\Middleware\ContextIdentityMiddleware

        routing: ~