security:
    enable_authenticator_manager: true
    providers:
        app_user_provider_email:
            entity:
                class: App\Entity\User
                property: email
        app_user_provider_id:
            entity:
                class: App\Entity\User
                property: id
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_USER: ~
        ROLE_SYS_API: ~
    password_hashers:
        App\Entity\User: 'auto'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        pub:
            pattern: ^/api/pub/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider_email
            json_login:
                check_path: auth_login
                success_handler: AnzuSystems\AuthBundle\Security\AuthenticationSuccessHandler
        adm:
            pattern: ^/api/adm/
            stateless: true
            provider: app_user_provider_id
            custom_authenticators:
                - AnzuSystems\AuthBundle\Security\Authentication\JwtAuthentication
    #        sys:
    #            pattern: ^/api/sys
    #            stateless: true
    #            custom_authenticators:
    #                - App\Security\Authentication\SysAuthenticator

    access_control:
#        - { path: ^/api/pub, roles: PUBLIC_ACCESS }
#        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/adm, roles: ROLE_USER }
#        - { path: ^/api/sys, roles: ROLE_SYS_API }
