anzu_systems_core_dam:
    storages:
        cms.audio:
            adapter: 'local'
            fallback_enabled: '%env(bool:CMS_AUDIO_FALLBACK_ENABLED)%'
            fallback_storage: cms.audio_fallback
            options:
                directory: '%kernel.project_dir%/var/mnt/data/audio'
        cms.public_audio:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/public-audio'
        cms.image:
            adapter: 'local'
            fallback_enabled: '%env(bool:CMS_IMAGE_FALLBACK_ENABLED)%'
            fallback_storage: cms.image_fallback
            options:
                directory: '%kernel.project_dir%/var/mnt/data/image'
        blog.image:
            adapter: 'local'
            fallback_enabled: '%env(bool:BLOG_IMAGE_FALLBACK_ENABLED)%'
            fallback_storage: blog.image_fallback
            options:
                directory: '%kernel.project_dir%/var/mnt/data/blog_image'
        cms.document:
            adapter: 'local'
            fallback_enabled: '%env(bool:CMS_DOCUMENT_FALLBACK_ENABLED)%'
            fallback_storage: cms.document_fallback
            options:
                directory: '%kernel.project_dir%/var/mnt/data/document'
        cms.video:
            adapter: 'local'
            fallback_enabled: '%env(bool:CMS_VIDEO_FALLBACK_ENABLED)%'
            fallback_storage: cms.video_fallback
            options:
                directory: '%kernel.project_dir%/var/mnt/data/video'
        ext.rtmp:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/rtmp'
        ext.scraper:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/ext_scraper'
        cms.chunk:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/chunk'
        cms.crop:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/crop'
        blog.crop:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/blog-crop'
        blog.chunk:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/blog-chunk'
        cms.image_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_IMAGE_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'assets'
        blog.image_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_BLOG_IMAGE_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'images'
        cms.audio_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_AUDIO_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'audios'
        cms.video_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_VIDEO_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'videos'
        cms.document_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_DOCUMENT_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'documents'

        cms.media_api.prod_storage:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.mediaapi_prod_client'
                bucket: 'mediaapi-content-production-bel'
                prefix: 'public/api-media/media/image'

        cms.media_api.storage:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.mediaapi_client'
                bucket: '%env(string:GCS_MEDIA_API_IMAGE_BUCKET)%'
                prefix: 'public/api-media/media/image'

        cms.media_api.local_storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/media'

        cms.media_api.fs1_storage:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: 'fs1sme-production-backup'
                prefix: 'web/sme/home'

        scraper.image_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_SCRAPER_IMAGE_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'images'
        scraper.image:
            adapter: 'local'
            fallback_enabled: '%env(bool:SCRAPER_IMAGE_FALLBACK_ENABLED)%'
            fallback_storage: scraper.image_fallback
            options:
                directory: '%kernel.project_dir%/var/mnt/data/scraper_image'
        scraper.crop:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/scraper_crop'
        scraper.chunk:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/scraper_chunk'
        pressNews.image_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_PRESS_NEWS_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'images'
        pressNews.image:
            adapter: 'local'
            fallback_enabled: '%env(bool:PRESS_NEWS_IMAGE_FALLBACK_ENABLED)%'
            fallback_storage: blog.image_fallback
            options:
                directory: '%kernel.project_dir%/var/mnt/data/press_news_image'
        pressNews.crop:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/press_news_image_crop'
        pressNews.chunk:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/mnt/data/press_news_image_chunk'
