# Anzu-Core-DAM project Azure Pipelines Continuous Deployment Release definition
# 1. Create release/hotfix branch in core-dam project
# 2. Build and push the anzu-core-dam image to Azure Container Registry
# 3. Tag the release/hotfix branch
# 4. Deploy to chosen environment
# 5. Merge release/hotfix branch to master and develop branches

name: $(rev:rrrr)_$(SHORT_RELEASE_TYPE)_$(VERSION)$(ENVIRONMENT_TAG)
appendCommitMessageToRunName: false

# Disable automatic pipeline trigger
trigger: none

# Setup runtime parameters
parameters:
  - name: version
    displayName: Version
    type: string
  - name: changelog
    displayName: Changelog
    type: string
    default: ' '
  - name: releaseType
    displayName: Release type
    type: string
    default: 'hotfix'
    values:
      - hotfix
      - release
  - name: runBranchInitialization
    displayName: Branch initialization
    type: boolean
    default: true
  - name: runBuild
    displayName: Docker build
    type: boolean
    default: true
  - name: runDeployment
    displayName: Deployment
    type: boolean
    default: false
  - name: environment
    displayName: Environment
    type: string
    default: 'devel'
    values:
      - devel
      - stage
      - production

# Setup variables
variables:
  - group: 'core-dam-${{ parameters.environment }}'
  - group: 'core-dam-${{ parameters.environment }}-secrets'
  # Application project name
  - name: APP_NAME
    value: 'core-dam'
  # Pipeline name shortcuts
  - ${{ if eq(parameters.releaseType, 'release') }}:
    - name: SHORT_RELEASE_TYPE
      value: 'R'
  - ${{ if eq(parameters.releaseType, 'hotfix') }}:
    - name: SHORT_RELEASE_TYPE
      value: 'H'
  - ${{ if parameters.runDeployment }}:
    - name: ENVIRONMENT_TAG
      value: '_${{ parameters.environment }}'
  - ${{ if not(parameters.runDeployment) }}:
    - name: ENVIRONMENT_TAG
      value: ''
  # Deploy environment
  - name: DEPLOY_ENV
    value: '${{ parameters.environment }}'
  # Application version
  - name: VERSION
    value: '${{ parameters.version }}'
  # Application container registry image repository
  - name: APP_DOCKER_IMAGE_REPOSITORY
    value: 'anzu-$(APP_NAME)'
  # Cron container registry image repository
  - name: CRON_DOCKER_IMAGE_REPOSITORY
    value: 'anzu-$(APP_NAME)-cron'
  # Application dockerfile location
  - name: APP_DOCKERFILE
    value: '$(Build.SourcesDirectory)/docker/app/kubernetes/Dockerfile'
  # Cron dockerfile location
  - name: CRON_DOCKERFILE
    value: '$(Build.SourcesDirectory)/docker/app-cron/kubernetes/Dockerfile'
  # Kubernetes migration job manifest filename
  - name: CONFIGURATION_MANIFEST_FILE_NAME
    value: 'configuration.yaml'
  # Kubernetes migration job name
  - name: JOB_MIGRATIONS_NAME
    value: '$(APP_NAME)-migrations'
  # Kubernetes migration job manifest filename
  - name: JOB_MIGRATIONS_MANIFEST_FILE_NAME
    value: 'migrations-job.yaml'
  # Kubernetes migration job execution timeout in seconds
  - name: JOB_EXECUTION_TIMEOUT_SECONDS
    value: '$(JOB_MIGRATIONS_EXECUTION_TIMEOUT_SECONDS)'
  # Kubernetes application deployment name
  - name: APP_KUBERNETES_DEPLOYMENT_NAME
    value: '$(APP_NAME)'
  # Kubernetes cron deployment name
  - name: CRON_KUBERNETES_DEPLOYMENT_NAME
    value: '$(APP_NAME)-cron'
  # Kubernetes service connection name
  - name: KUBERNETES_SERVICE_CONNECTION_NAME
    value: '$(DEPLOYMENT_KUBERNETES_NAMESPACE)-${{ parameters.environment }}'
  # Kubernetes namespace
  - name: KUBERNETES_NAMESPACE
    value: '$(DEPLOYMENT_KUBERNETES_NAMESPACE)'

# Checkout azure ci template repository
resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/azure-ci-template

# Pipeline definition
extends:
  template: composer-release-k8s.yaml@templates
  parameters:
    containerDockerImageVersion: php83
    containerDockerImageVariant: cli-ci-node-vipsffmpeg-xdebug
    releaseType: ${{ parameters.releaseType }}
    version: ${{ parameters.version }}
    changelog: ${{ parameters.changelog }}
    runBranchInitialization: ${{ parameters.runBranchInitialization }}
    runBuild: ${{ parameters.runBuild }}
    appDockerImageRepository: $(APP_DOCKER_IMAGE_REPOSITORY)
    cronDockerImageRepository: $(CRON_DOCKER_IMAGE_REPOSITORY)
    appDockerfile: $(APP_DOCKERFILE)
    cronDockerfile: $(CRON_DOCKERFILE)
    runDeployment: ${{ parameters.runDeployment }}
    environment: ${{ parameters.environment }}
    kubernetesConfigurationManifestFileName: $(CONFIGURATION_MANIFEST_FILE_NAME)
    kubernetesJobManifestFileName: $(JOB_MIGRATIONS_MANIFEST_FILE_NAME)
    appKubernetesJobName: $(JOB_MIGRATIONS_NAME)
    appKubernetesDeploymentName: $(APP_KUBERNETES_DEPLOYMENT_NAME)
    cronKubernetesDeploymentName: $(CRON_KUBERNETES_DEPLOYMENT_NAME)
    kubernetesServiceConnectionName: $(KUBERNETES_SERVICE_CONNECTION_NAME)
    kubernetesNamespace: $(KUBERNETES_NAMESPACE)
