services:
  core-dam:
    build:
      args:
        - DOCKER_USER=${DOCKER_USER:-user}
        - DOCKER_USER_ID=${DOCKER_USER_ID:-1000}
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:-1000}
      context: .
      dockerfile: ./docker/app/local/Dockerfile
    environment:
      - VIRTUAL_HOST=core-dam.sme.localhost,image.smedata.localhost,audio.smedata.localhost,admin-image.smedata.localhost
      - VIRTUAL_PORT=${NGINX_PORT:-8130}
      - NGINX_PORT=${NGINX_PORT:-8130}
    external_links:
      - local-proxy:core-dam.sme.localhost
      - local-proxy:central.sme.localhost
    env_file:
      - .env.docker.dist
      - .env.docker.local
    secrets:
      - ssh_private_key
    volumes:
      - .:/var/www/html:cached
      - ./tests/coverage:/opt/phpstorm-coverage:cached
    ports:
      - ${NGINX_PORT:-8130}:${NGINX_PORT:-8130}
    hostname: core-dam
    networks:
      - ${DOCKER_NETWORK_NAME:-petitpress_network}

  core-dam-cron:
    build:
      args:
        - DOCKER_USER=${DOCKER_USER:-user}
        - DOCKER_USER_ID=${DOCKER_USER_ID:-1000}
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:-1000}
      context: .
      dockerfile: ./docker/app-cron/local/Dockerfile
    external_links:
      - local-proxy:core-dam.sme.localhost
    env_file:
      - .env.docker.dist
      - .env.docker.local
    volumes:
      - .:/var/www/html:cached
    hostname: core-dam-cron
    networks:
      - ${DOCKER_NETWORK_NAME:-petitpress_network}

secrets:
  ssh_private_key:
    file: ${DOCKER_SSH_PRV_KEY_FILE:-~/.ssh/id_rsa}

networks:
  petitpress_network:
    external: true
