apiVersion: v1
kind: ConfigMap
metadata:
  name: #{APP_NAME}#
  labels:
    app: #{APP_NAME}#
    type: application
data:
  ANZU_JOBS_BATCH_SIZE: "#{ANZU_JOBS_BATCH_SIZE}#"
  ANZU_JOBS_MAX_EXEC_TIME: "#{ANZU_JOBS_MAX_EXEC_TIME}#"
  ANZU_JOBS_MAX_MEMORY: "#{ANZU_JOBS_MAX_MEMORY}#"
  ANZU_JOBS_NO_JOB_IDLE_TIME: "#{ANZU_JOBS_NO_JOB_IDLE_TIME}#"
  ANZU_MONGODB_APP_LOG_DB: "#{ANZU_MONGODB_APP_LOG_DB}#"
  ANZU_MONGODB_APP_LOG_SSL: "#{ANZU_MONGODB_APP_LOG_SSL}#"
  ANZU_MONGODB_APP_LOG_URI: "#{ANZU_MONGODB_APP_LOG_URI}#"
  ANZU_MONGODB_APP_LOG_USERNAME: "#{ANZU_MONGODB_APP_LOG_USERNAME}#"
  ANZU_MONGODB_AUDIT_LOG_DB: "#{ANZU_MONGODB_AUDIT_LOG_DB}#"
  ANZU_MONGODB_AUDIT_LOG_SSL: "#{ANZU_MONGODB_AUDIT_LOG_SSL}#"
  ANZU_MONGODB_AUDIT_LOG_URI: "#{ANZU_MONGODB_AUDIT_LOG_URI}#"
  ANZU_MONGODB_AUDIT_LOG_USERNAME: "#{ANZU_MONGODB_AUDIT_LOG_USERNAME}#"
  ANZU_NOTIFICATION_DOMAIN: "#{ANZU_NOTIFICATION_DOMAIN}#"
  ANZU_CMS_API_HOST: "#{ANZU_CMS_API_HOST}#"
  APP_CMS_AUDIO_MAX_SIZE: "#{APP_CMS_AUDIO_MAX_SIZE}#"
  APP_CMS_BLOG_MAX_SIZE: "#{APP_CMS_BLOG_MAX_SIZE}#"
  APP_CMS_DOCUMENT_MAX_SIZE: "#{APP_CMS_DOCUMENT_MAX_SIZE}#"
  APP_CMS_IMAGE_MAX_SIZE: "#{APP_CMS_IMAGE_MAX_SIZE}#"
  APP_CMS_VIDEO_MAX_SIZE: "#{APP_CMS_VIDEO_MAX_SIZE}#"
  APP_DEBUG: "#{APP_DEBUG}#"
  APP_DEPLOY_ENV: "#{DEPLOY_ENV}#"
  APP_ENV: "#{APP_ENV}#"
  APP_HOST: "#{APP_HOST}#"
  APP_READ_ONLY_MODE: "#{APP_READ_ONLY_MODE}#"
  APP_SIZE_MAX_CHUNK_SIZE: "#{APP_SIZE_MAX_CHUNK_SIZE}#"
  APP_SIZE_MIN_CHUNK_SIZE: "#{APP_SIZE_MIN_CHUNK_SIZE}#"
  AUTH_OAUTH2_ACCESS_TOKEN_URL: "#{AUTH_OAUTH2_ACCESS_TOKEN_URL}#"
  AUTH_OAUTH2_AUTHORIZE_URL: "#{AUTH_OAUTH2_AUTHORIZE_URL}#"
  AUTH_OAUTH2_REDIRECT_URL: "#{AUTH_OAUTH2_REDIRECT_URL}#"
  AUTH_OAUTH2_USER_INFO_BY_EMAIL_URL: "#{AUTH_OAUTH2_USER_INFO_BY_EMAIL_URL}#"
  AUTH_OAUTH2_USER_INFO_URL: "#{AUTH_OAUTH2_USER_INFO_URL}#"
  AUTH_REDIRECT_DEFAULT_URL: "#{AUTH_REDIRECT_DEFAULT_URL}#"
  AUTH_REDIRECT_QUERY_URL_ALLOWED_PATTERN: "#{AUTH_REDIRECT_QUERY_URL_ALLOWED_PATTERN}#"
  AUTH_UGC_JWT_PAYLOAD_PART_COOKIE_NAME: "#{AUTH_UGC_JWT_PAYLOAD_PART_COOKIE_NAME}#"
  AUTH_UGC_JWT_SIGNATURE_PART_COOKIE_NAME: "#{AUTH_UGC_JWT_SIGNATURE_PART_COOKIE_NAME}#"
  BLOG_IMAGE_FALLBACK_ENABLED: "#{BLOG_IMAGE_FALLBACK_ENABLED}#"
  CLOUD_FLARE_API_HOST: "#{CLOUD_FLARE_API_HOST}#"
  CLOUD_FLARE_API_ZONE: "#{CLOUD_FLARE_API_ZONE}#"
  CMS_AUDIO_FALLBACK_ENABLED: "#{CMS_AUDIO_FALLBACK_ENABLED}#"
  CMS_DOCUMENT_FALLBACK_ENABLED: "#{CMS_DOCUMENT_FALLBACK_ENABLED}#"
  CMS_IMAGE_FALLBACK_ENABLED: "#{CMS_IMAGE_FALLBACK_ENABLED}#"
  CMS_VIDEO_FALLBACK_ENABLED: "#{CMS_VIDEO_FALLBACK_ENABLED}#"
  COOKIE_DOMAIN: "#{COOKIE_DOMAIN}#"
  COOKIE_SECURE: "#{COOKIE_SECURE}#"
  CORE_DAM_CACHE_PROXY_PURGE_ENABLED: "#{CORE_DAM_CACHE_PROXY_PURGE_ENABLED}#"
  CORE_DAM_CACHE_PURGE_URL: "#{CORE_DAM_CACHE_PURGE_URL}#"
  CORE_DAM_CACHE_PURGE_HOST: "#{CORE_DAM_CACHE_PURGE_HOST}#"
  CORE_DAM_CDN_PURGE_ENABLED: "#{CORE_DAM_CDN_PURGE_ENABLED}#"
  CACHE_PURGE_DEBUG_ENABLED: "#{CACHE_PURGE_DEBUG_ENABLED}#"
  CRON_KILL_TIMEOUT: "#{CRON_KILL_TIMEOUT}#"
  CRON_TERM_TIMEOUT: "#{CRON_TERM_TIMEOUT}#"
  DISTRIBUTION_AUTH_REDIRECT_URL: "#{DISTRIBUTION_AUTH_REDIRECT_URL}#"
  DISTRIBUTION_JW_CMS_ICON_PATH: "#{DISTRIBUTION_JW_CMS_ICON_PATH}#"
  DISTRIBUTION_JW_CMS_SITE_ID: "#{DISTRIBUTION_JW_CMS_SITE_ID}#"
  DISTRIBUTION_YOUTUBE_CMS_MAIN_CHANNEL_ID: "#{DISTRIBUTION_YOUTUBE_CMS_MAIN_CHANNEL_ID}#"
  DISTRIBUTION_YOUTUBE_CMS_MAIN_ICON_PATH: "#{DISTRIBUTION_YOUTUBE_CMS_MAIN_ICON_PATH}#"
  DISTRIBUTION_YOUTUBE_CMS_MAIN_OAUTH_CREDENTIALS: "/var/www/html/var/secure/youtube/yt_oauth2_credentials.json"
  DISTRIBUTION_YOUTUBE_CMS_MAIN_REDIRECT_URL: "#{DISTRIBUTION_YOUTUBE_CMS_MAIN_REDIRECT_URL}#"
  DISTRIBUTION_YOUTUBE_REDIRECT_URI: "#{DISTRIBUTION_YOUTUBE_REDIRECT_URI}#"
  DOCTRINE_CACHE_ENABLED: "#{DOCTRINE_CACHE_ENABLED}#"
  DOMAIN_ADMIN_IMAGE_CACHE_TTL: "#{DOMAIN_ADMIN_IMAGE_CACHE_TTL}#"
  DOMAIN_ADMIN_IMAGE_MAX_AGE: "#{DOMAIN_ADMIN_IMAGE_MAX_AGE}#"
  DOMAIN_ADMIN_IMAGE_PUBLIC: "#{DOMAIN_ADMIN_IMAGE_PUBLIC}#"
  DOMAIN_ADMIN_IMAGE: "#{DOMAIN_ADMIN_IMAGE}#"
  DOMAIN_CORE_DAM_API: "#{DOMAIN_CORE_DAM_API}#"
  DOMAIN_PUBLIC_AUDIO: "#{DOMAIN_PUBLIC_AUDIO}#"
  DOMAIN_PUBLIC_DOCUMENT: "#{DOMAIN_PUBLIC_DOCUMENT}#"
  DOMAIN_PUBLIC_IMAGE_CACHE_TTL: "#{DOMAIN_PUBLIC_IMAGE_CACHE_TTL}#"
  DOMAIN_PUBLIC_IMAGE_MAX_AGE: "#{DOMAIN_PUBLIC_IMAGE_MAX_AGE}#"
  DOMAIN_PUBLIC_IMAGE_PUBLIC: "#{DOMAIN_PUBLIC_IMAGE_PUBLIC}#"
  DOMAIN_PUBLIC_IMAGE: "#{DOMAIN_PUBLIC_IMAGE}#"
  DOMAIN_REDIRECT_CORE_DAM: "#{DOMAIN_REDIRECT_CORE_DAM}#"
  DOMAIN_PUBLIC_DOCUMENT_MAX_AGE: "#{DOMAIN_PUBLIC_DOCUMENT_MAX_AGE}#"
  DOMAIN_PUBLIC_DOCUMENT_CACHE_TTL: "#{DOMAIN_PUBLIC_DOCUMENT_CACHE_TTL}#"
  DOMAIN_PUBLIC_DOCUMENT_PUBLIC: "#{DOMAIN_PUBLIC_DOCUMENT_PUBLIC}#"
  ELASTIC_HOSTS: "#{ELASTIC_HOSTS}#"
  ELASTIC_INDEX_PREFIX: "#{ELASTIC_INDEX_PREFIX}#"
  ELASTIC_USERNAME: "#{ELASTIC_USERNAME}#"
  FIXTURES_ENV: "#{FIXTURES_ENV}#"
  GCLOUD_PROJECT: "#{GCLOUD_PROJECT}#"
  GCS_AUDIO_FALLBACK_STORAGE_BUCKET: "#{GCS_AUDIO_FALLBACK_STORAGE_BUCKET}#"
  GCS_AUDIO_STORAGE_BUCKET: "#{GCS_AUDIO_STORAGE_BUCKET}#"
  GCS_BLOG_IMAGE_FALLBACK_STORAGE_BUCKET: "#{GCS_BLOG_IMAGE_FALLBACK_STORAGE_BUCKET}#"
  GCS_BLOG_IMAGE_STORAGE_BUCKET: "#{GCS_BLOG_IMAGE_STORAGE_BUCKET}#"
  GCS_DOCUMENT_FALLBACK_STORAGE_BUCKET: "#{GCS_DOCUMENT_FALLBACK_STORAGE_BUCKET}#"
  GCS_DOCUMENT_STORAGE_BUCKET: "#{GCS_DOCUMENT_STORAGE_BUCKET}#"
  GCS_EXT_SCRAPER_STORAGE_BUCKET: "#{GCS_EXT_SCRAPER_STORAGE_BUCKET}#"
  GCS_GENERAL_DOCUMENT_BUCKET: "#{GCS_GENERAL_DOCUMENT_BUCKET}#"
  GCS_IMAGE_FALLBACK_STORAGE_BUCKET: "#{GCS_IMAGE_FALLBACK_STORAGE_BUCKET}#"
  GCS_IMAGE_STORAGE_BUCKET: "#{GCS_IMAGE_STORAGE_BUCKET}#"
  GCS_MEDIA_API_IMAGE_BUCKET: "#{GCS_MEDIA_API_IMAGE_BUCKET}#"
  GCS_PEOPLE_FALLBACK_STORAGE_BUCKET: "#{GCS_PEOPLE_FALLBACK_STORAGE_BUCKET}#"
  GCS_PEOPLE_IMAGE_STORAGE_BUCKET: "#{GCS_PEOPLE_IMAGE_STORAGE_BUCKET}#"
  GCS_PRESS_NEWS_FALLBACK_STORAGE_BUCKET: "#{GCS_PRESS_NEWS_FALLBACK_STORAGE_BUCKET}#"
  GCS_PRESS_NEWS_IMAGE_STORAGE_BUCKET: "#{GCS_PRESS_NEWS_IMAGE_STORAGE_BUCKET}#"
  GCS_PUBLIC_AUDIO_STORAGE_BUCKET: "#{GCS_PUBLIC_AUDIO_STORAGE_BUCKET}#"
  GCS_RTMP_STORAGE_BUCKET: "#{GCS_RTMP_STORAGE_BUCKET}#"
  GCS_SCRAPER_IMAGE_FALLBACK_STORAGE_BUCKET: "#{GCS_SCRAPER_IMAGE_FALLBACK_STORAGE_BUCKET}#"
  GCS_SCRAPER_IMAGE_STORAGE_BUCKET: "#{GCS_SCRAPER_IMAGE_STORAGE_BUCKET}#"
  GCS_VIDEO_FALLBACK_STORAGE_BUCKET: "#{GCS_VIDEO_FALLBACK_STORAGE_BUCKET}#"
  GCS_VIDEO_STORAGE_BUCKET: "#{GCS_VIDEO_STORAGE_BUCKET}#"
  GCS_DENNIK_SPORT_IMAGE_FALLBACK_STORAGE_BUCKET: "#{GCS_DENNIK_SPORT_IMAGE_FALLBACK_STORAGE_BUCKET}#"
  GCS_DENNIK_SPORT_IMAGE_STORAGE_BUCKET: "#{GCS_DENNIK_SPORT_IMAGE_STORAGE_BUCKET}#"
  GCS_DENNIK_SPORT_DOCUMENT_STORAGE_BUCKET: "#{GCS_DENNIK_SPORT_DOCUMENT_STORAGE_BUCKET}#"
  GCS_DENNIK_SPORT_DOCUMENT_FALLBACK_STORAGE_BUCKET: "#{GCS_DENNIK_SPORT_DOCUMENT_FALLBACK_STORAGE_BUCKET}#"
  GOOGLE_BUCKET_CREDENTIALS: "/var/www/html/var/secure/google/storage-bucket-credentials.json"
  GOOGLE_FALLBACK_BUCKET_CREDENTIALS: "/var/www/html/var/secure/google/fallback-storage-bucket-credentials.json"
  GOOGLE_GENERAL_PROD_BUCKET_CREDENTIALS: "/var/www/html/var/secure/google/general-production-storage-bucket-credentials.json"
  GOOGLE_MEDIA_API_BUCKET_CREDENTIALS: "/var/www/html/var/secure/google/mediaapi-storage-bucket-credentials.json"
  IMAGE_ADMIN_CC_TTL: "#{IMAGE_ADMIN_CC_TTL}#"
  IMAGE_ADMIN_MAX_AGE: "#{IMAGE_ADMIN_MAX_AGE}#"
  IMAGE_PUBLIC_CC_TTL: "#{IMAGE_PUBLIC_CC_TTL}#"
  IMAGE_PUBLIC_MAX_AGE: "#{IMAGE_PUBLIC_MAX_AGE}#"
  MEDIA_API_HOST: "#{MEDIA_API_HOST}#"
  MESSENGER_ASSET_CHANGE_STATE_TOPIC: "#{MESSENGER_ASSET_CHANGE_STATE_TOPIC}#"
  MESSENGER_ASSET_METADATA_PROCESS_TOPIC: "#{MESSENGER_ASSET_METADATA_PROCESS_TOPIC}#"
  MESSENGER_AUDIO_FILE_CHANGE_STATE_TOPIC: "#{MESSENGER_AUDIO_FILE_CHANGE_STATE_TOPIC}#"
  MESSENGER_DISTRIBUTION_REMOTE_PROCESSED_CHECK_TOPIC: "#{MESSENGER_DISTRIBUTION_REMOTE_PROCESSED_CHECK_TOPIC}#"
  MESSENGER_DISTRIBUTION_TOPIC: "#{MESSENGER_DISTRIBUTION_TOPIC}#"
  MESSENGER_DOCUMENT_FILE_CHANGE_STATE_TOPIC: "#{MESSENGER_DOCUMENT_FILE_CHANGE_STATE_TOPIC}#"
  MESSENGER_IMAGE_FILE_CHANGE_STATE_TOPIC: "#{MESSENGER_IMAGE_FILE_CHANGE_STATE_TOPIC}#"
  MESSENGER_PROPERTY_REFRESH_TOPIC: "#{MESSENGER_PROPERTY_REFRESH_TOPIC}#"
  MESSENGER_TRANSPORT_DSN: "#{MESSENGER_TRANSPORT_DSN}#"
  MESSENGER_VIDEO_FILE_CHANGE_STATE_TOPIC: "#{MESSENGER_VIDEO_FILE_CHANGE_STATE_TOPIC}#"
  NEWRELIC_APP_NAME: "#{NEWRELIC_APP_NAME}#"
  NEWRELIC_ENABLED: "#{NEWRELIC_ENABLED}#"
  NGINX_ACCESS_LOG: "/var/www/html/var/log/nginx_access.log main"
  NGINX_ALLOWED_ORIGINS_REGEX: "#{NGINX_ALLOWED_ORIGINS_REGEX}#"
  NGINX_CLIENT_BODY_BUFFER_SIZE: "#{NGINX_CLIENT_BODY_BUFFER_SIZE}#"
  NGINX_CLIENT_MAX_BODY_SIZE: "#{NGINX_CLIENT_MAX_BODY_SIZE}#"
  NGINX_ERROR_LOG: "/var/www/html/var/log/nginx_error.log warn"
  NGINX_HEALTHCHECK_START_ENABLED: "false"
  NGINX_STATIC_LOCATION_REGEX: "\\.(ico|css|js|bmp|eot|woff|woff2|ttf)$$"
  PEOPLE_IMAGE_FALLBACK_ENABLED: "#{PEOPLE_IMAGE_FALLBACK_ENABLED}#"
  DENNIK_SPORT_IMAGE_FALLBACK_ENABLED: "#{DENNIK_SPORT_IMAGE_FALLBACK_ENABLED}#"
  DENNIK_SPORT_DOCUMENT_FALLBACK_ENABLED: "#{DENNIK_SPORT_DOCUMENT_FALLBACK_ENABLED}#"
  PHP_ACCESS_LOG: "/var/www/html/var/log/fpm_access.log"
  PHP_ERROR_LOG: "/var/www/html/var/log/fpm_error.log"
  PHP_MAX_EXECUTION_TIME: "#{PHP_MAX_EXECUTION_TIME}#"
  PHP_OPCACHE_PRELOAD_PATH: "/var/www/html/var/cache/prod/App_KernelProdContainer.preload.php"
  PHP_PM_MAX_CHILDREN: "#{PHP_PM_MAX_CHILDREN}#"
  PHP_SLOW_LOG: "/var/www/html/var/log/fpm_error.log"
  PHP_UPLOAD_MAX_FILESIZE: "#{PHP_UPLOAD_MAX_FILESIZE}#"
  PHP_ZEND_MAX_ALLOWED_STACK_SIZE: "#{PHP_ZEND_MAX_ALLOWED_STACK_SIZE}#"
  PRESS_NEWS_IMAGE_FALLBACK_ENABLED: "#{PRESS_NEWS_IMAGE_FALLBACK_ENABLED}#"
  PUBLIC_IMAGE_ADMIN_DOMAIN: "#{PUBLIC_IMAGE_ADMIN_DOMAIN}#"
  PUBLIC_IMAGE_DOMAIN: "#{PUBLIC_IMAGE_DOMAIN}#"
  PUBSUB_EMULATOR_HOST: ""
  PURGE_CACHE_XKEY_ENABLED: "#{PURGE_CACHE_XKEY_ENABLED}#"
  PURGE_CDN_ENABLED: "#{PURGE_CDN_ENABLED}#"
  RSS_JW_DISTRIBUTE: "#{RSS_JW_DISTRIBUTE}#"
  SCRAPER_IMAGE_FALLBACK_ENABLED: "#{SCRAPER_IMAGE_FALLBACK_ENABLED}#"
  SECURE_CHANNEL: "#{SECURE_CHANNEL}#"
  SENTRY_PROFILES_SAMPLE_RATE: "#{SENTRY_PROFILES_SAMPLE_RATE}#"
  SENTRY_RELAY_AUTOSTART_ENABLED: "true"
  SENTRY_TRACES_SAMPLE_RATE: "#{SENTRY_TRACES_SAMPLE_RATE}#"
  SSO_CLIENT_ID: "#{SSO_CLIENT_ID}#"
  SSO_PUBLIC_CERT_PATH: "/var/www/html/var/secure/sso/central-oauth2-public-key.pem"
  SSO_USER_INFO_URL: "#{SSO_USER_INFO_URL}#"
  SUPERVISOR_MESSENGER_LIMIT: "10"
  SUPERVISOR_MESSENGER_NUMPROCS: "1"
  SUPERVISOR_MESSENGER_TIME_LIMIT: "600"
---
apiVersion: v1
kind: Secret
metadata:
  name: #{APP_NAME}#
  labels:
    app: #{APP_NAME}#
    type: application
type: Opaque
stringData:
  ANZU_DAM_NOTIFICATION_API_TOKEN: "#{core-dam-anzu-dam-notification-api-token}#"
  ANZU_MONGODB_APP_LOG_PASSWORD: "#{mongodb-cluster-password-core-dam}#"
  ANZU_MONGODB_AUDIT_LOG_PASSWORD: "#{mongodb-cluster-password-core-dam}#"
  APP_SECRET: "#{core-dam-app-secret}#"
  ANZU_CMS_API_TOKEN: "#{core-dam-anzu-cms-token}#"
  ASSET_EXTERNAL_PROVIDER_UNSPLASH_CMS_ACCESS_KEY: "#{core-dam-asset-external-provider-unsplash-cms-access-key}#"
  AUTH_JWT_PRIVATE_CERT: "#{anzu-auth-jwt-private-cert}#"
  AUTH_JWT_PUBLIC_CERT: "#{anzu-auth-jwt-public-cert}#"
  AUTH_OAUTH2_CLIENT_SECRET: "#{core-dam-auth-oauth2-client-secret}#"
  AUTH_OAUTH2_JWT_PUBLIC_CERT: "#{core-dam-auth-oauth2-jwt-public-cert}#"
  AUTH_OAUTH2_STATE_TOKEN_SALT: "#{core-dam-auth-oauth2-state-token-salt}#"
  AUTH_UGC_IMP_JWT_PUBLIC_CERT: "#{core-dam-auth-ugc-imp-jwt-public-cert}#"
  AUTH_UGC_JWT_PUBLIC_CERT: "#{core-dam-auth-ugc-jwt-public-cert}#"
  CLOUD_FLARE_API_TOKEN: "#{core-dam-cloud-flare-api-token}#"
  DB_BLOG_URL: "mysql://#{DB_CORE_DAM_USER}#:#{mysql-user-app-core-dam-pwd}#@#{DB_CORE_DAM_HOST}#:#{DB_CORE_DAM_PORT}#/#{DB_BLOG_NAME}#?serverVersion=#{DB_SERVER_VERSION}#"
  DB_CORE_DAM_URL: "mysql://#{DB_CORE_DAM_USER}#:#{mysql-user-app-core-dam-pwd}#@#{DB_CORE_DAM_HOST}#:#{DB_CORE_DAM_PORT}#/#{DB_CORE_DAM_NAME}#?serverVersion=#{DB_SERVER_VERSION}#"
  DB_DAM_LEGACY_URL: "mysql://#{DB_CORE_DAM_USER}#:#{mysql-user-app-core-dam-pwd}#@#{DB_CORE_DAM_HOST}#:#{DB_CORE_DAM_PORT}#/#{DB_DAM_LEGACY_NAME}#?serverVersion=#{DB_SERVER_VERSION}#"
  DB_DAM_MEDIA_API_MIG_NAME_URL: "mysql://#{DB_CORE_DAM_USER}#:#{mysql-user-app-core-dam-pwd}#@#{DB_CORE_DAM_HOST}#:#{DB_CORE_DAM_PORT}#/#{DB_DAM_MEDIA_API_MIG_NAME}#?serverVersion=#{DB_SERVER_VERSION}#"
  DB_MEDIA_API_URL: "mysql://#{DB_MEDIA_API_USER}#:#{core-dam-mysql-mediaapi-db-password}#@#{DB_MEDIA_API_HOST}#:#{DB_MEDIA_API_PORT}#/#{DB_MEDIA_API_NAME}#?serverVersion=#{DB_MEDIA_API_SERVER_VERSION}#"
  DISTRIBUTION_ARTEMIS_CMS_API_TOKEN: "#{core-dam-distribution-artemis-cms-api-token}#"
  DISTRIBUTION_JW_CMS_SECRET_V2: "#{core-dam-distribution-jw-cms-secret-v2}#"
  ELASTIC_PASSWORD: "#{elasticsearch-user-app-core-dam-pwd}#"
  GOOGLE_PUBSUB_SA_KEY: "#{anzu-app-pubsub-sa}#"
  HEALTH_CHECK_ACCESS_TOKEN: "#{core-dam-health-check-access-token}#"
  MEDIA_API_TOKEN: "#{core-dam-media-api-token}#"
  NEWRELIC_LICENSE: "#{newrelic-license}#"
  SENTRY_DSN: "#{core-dam-sentry-relay-dsn}#"
  YOUTUBE_API_KEY: "#{core-dam-youtube-api-key}#"
