apiVersion: v1
kind: ConfigMap
metadata:
  name: #{APP_NAME}#
  labels:
    app: #{APP_NAME}#
    type: application
data:
  ANZU_MONGODB_APP_LOG_DB: "#{ANZU_MONGODB_APP_LOG_DB}#"
  ANZU_MONGODB_APP_LOG_SSL: "#{ANZU_MONGODB_APP_LOG_SSL}#"
  ANZU_MONGODB_APP_LOG_URI: "#{ANZU_MONGODB_APP_LOG_URI}#"
  ANZU_MONGODB_APP_LOG_USERNAME: "#{ANZU_MONGODB_APP_LOG_USERNAME}#"
  ANZU_MONGODB_AUDIT_LOG_DB: "#{ANZU_MONGODB_AUDIT_LOG_DB}#"
  ANZU_MONGODB_AUDIT_LOG_SSL: "#{ANZU_MONGODB_AUDIT_LOG_SSL}#"
  ANZU_MONGODB_AUDIT_LOG_URI: "#{ANZU_MONGODB_AUDIT_LOG_URI}#"
  ANZU_MONGODB_AUDIT_LOG_USERNAME: "#{ANZU_MONGODB_AUDIT_LOG_USERNAME}#"
  ANZU_NOTIFICATION_DOMAIN: "#{ANZU_NOTIFICATION_DOMAIN}#"
  APP_CMS_AUDIO_MAX_SIZE: "#{APP_CMS_AUDIO_MAX_SIZE}#"
  APP_CMS_BLOG_MAX_SIZE: "#{APP_CMS_BLOG_MAX_SIZE}#"
  APP_CMS_DOCUMENT_MAX_SIZE: "#{APP_CMS_DOCUMENT_MAX_SIZE}#"
  APP_CMS_IMAGE_MAX_SIZE: "#{APP_CMS_IMAGE_MAX_SIZE}#"
  APP_CMS_VIDEO_MAX_SIZE: "#{APP_CMS_VIDEO_MAX_SIZE}#"
  APP_DEBUG: "#{APP_DEBUG}#"
  APP_ENV: "#{APP_ENV}#"
  APP_HOST: "#{APP_HOST}#"
  APP_READ_ONLY_MODE: "#{APP_READ_ONLY_MODE}#"
  APP_SIZE_MAX_CHUNK_SIZE: "#{APP_SIZE_MAX_CHUNK_SIZE}#"
  APP_SIZE_MIN_CHUNK_SIZE: "#{APP_SIZE_MIN_CHUNK_SIZE}#"
  APP_TRUSTED_PROXIES: "#{APP_TRUSTED_PROXIES}#"
  AUTH_JWT_PUBLIC_CERT: "#{AUTH_JWT_PUBLIC_CERT}#"
  AUTH_OAUTH2_ACCESS_TOKEN_URL: "#{AUTH_OAUTH2_ACCESS_TOKEN_URL}#"
  AUTH_OAUTH2_AUTHORIZE_URL: "#{AUTH_OAUTH2_AUTHORIZE_URL}#"
  AUTH_OAUTH2_JWT_PUBLIC_CERT: "#{AUTH_OAUTH2_JWT_PUBLIC_CERT}#"
  AUTH_OAUTH2_REDIRECT_URL: "#{AUTH_OAUTH2_REDIRECT_URL}#"
  AUTH_REDIRECT_DEFAULT_URL: "#{AUTH_REDIRECT_DEFAULT_URL}#"
  AUTH_REDIRECT_QUERY_URL_ALLOWED_PATTERN: "#{AUTH_REDIRECT_QUERY_URL_ALLOWED_PATTERN}#"
  AUTH_UGC_IMP_JWT_PUBLIC_CERT: "#{AUTH_UGC_IMP_JWT_PUBLIC_CERT}#"
  AUTH_UGC_JWT_PAYLOAD_PART_COOKIE_NAME: "#{AUTH_UGC_JWT_PAYLOAD_PART_COOKIE_NAME}#"
  AUTH_UGC_JWT_PUBLIC_CERT: "#{AUTH_UGC_JWT_PUBLIC_CERT}#"
  AUTH_UGC_JWT_SIGNATURE_PART_COOKIE_NAME: "#{AUTH_UGC_JWT_SIGNATURE_PART_COOKIE_NAME}#"
  BLOG_IMAGE_FALLBACK_ENABLED: "#{BLOG_IMAGE_FALLBACK_ENABLED}#"
  CMS_AUDIO_FALLBACK_ENABLED: "#{CMS_AUDIO_FALLBACK_ENABLED}#"
  CMS_DOCUMENT_FALLBACK_ENABLED: "#{CMS_DOCUMENT_FALLBACK_ENABLED}#"
  CMS_IMAGE_FALLBACK_ENABLED: "#{CMS_IMAGE_FALLBACK_ENABLED}#"
  CMS_VIDEO_FALLBACK_ENABLED: "#{CMS_VIDEO_FALLBACK_ENABLED}#"
  COOKIE_DOMAIN: "#{COOKIE_DOMAIN}#"
  COOKIE_SECURE: "#{COOKIE_SECURE}#"
  CRON_KILL_TIMEOUT: "#{CRON_KILL_TIMEOUT}#"
  CRON_TERM_TIMEOUT: "#{CRON_TERM_TIMEOUT}#"
  DISTRIBUTION_ARTEMIS_CMS_API_CERT_PATH: "#{DISTRIBUTION_ARTEMIS_CMS_API_CERT_PATH}#"
  DISTRIBUTION_ARTEMIS_CMS_API_KEY_PATH: "#{DISTRIBUTION_ARTEMIS_CMS_API_KEY_PATH}#"
  DISTRIBUTION_ARTEMIS_CMS_ENDPOINT: "#{DISTRIBUTION_ARTEMIS_CMS_ENDPOINT}#"
  DISTRIBUTION_AUTH_REDIRECT_URL: "#{DISTRIBUTION_AUTH_REDIRECT_URL}#"
  DISTRIBUTION_JW_CMS_SITE_ID: "#{DISTRIBUTION_JW_CMS_SITE_ID}#"
  DISTRIBUTION_YOUTUBE_CMS_FICI_CHANNEL_ID: "#{DISTRIBUTION_YOUTUBE_CMS_FICI_CHANNEL_ID}#"
  DISTRIBUTION_YOUTUBE_CMS_FICI_OAUTH_CREDENTIALS: "/var/www/html/var/secure/youtube/yt_oauth2_credentials.json"
  DISTRIBUTION_YOUTUBE_CMS_FICI_REDIRECT_URL: "#{DISTRIBUTION_YOUTUBE_CMS_FICI_REDIRECT_URL}#"
  DISTRIBUTION_YOUTUBE_CMS_MAIN_CHANNEL_ID: "#{DISTRIBUTION_YOUTUBE_CMS_MAIN_CHANNEL_ID}#"
  DISTRIBUTION_YOUTUBE_CMS_MAIN_OAUTH_CREDENTIALS: "/var/www/html/var/secure/youtube/yt_oauth2_credentials.json"
  DISTRIBUTION_YOUTUBE_CMS_MAIN_REDIRECT_URL: "#{DISTRIBUTION_YOUTUBE_CMS_MAIN_REDIRECT_URL}#"
  DOCTRINE_CACHE_ENABLED: "#{DOCTRINE_CACHE_ENABLED}#"
  DOMAIN_ADMIN_WEB: "#{DOMAIN_ADMIN_WEB}#"
  DOMAIN_CMS_WEB: "#{DOMAIN_CMS_WEB}#"
  DOMAIN_CORE_DAM_API: "#{DOMAIN_CORE_DAM_API}#"
  ELASTIC_HOSTS: "#{ELASTIC_HOSTS}#"
  ELASTIC_INDEX_PREFIX: "#{ELASTIC_INDEX_PREFIX}#"
  FIXTURES_ENV: "#{FIXTURES_ENV}#"
  GCLOUD_PROJECT: "#{GCLOUD_PROJECT}#"
  GCS_AUDIO_FALLBACK_STORAGE_BUCKET: "#{GCS_AUDIO_FALLBACK_STORAGE_BUCKET}#"
  GCS_AUDIO_STORAGE_BUCKET: "#{GCS_AUDIO_STORAGE_BUCKET}#"
  GCS_BLOG_IMAGE_FALLBACK_STORAGE_BUCKET: "#{GCS_BLOG_IMAGE_FALLBACK_STORAGE_BUCKET}#"
  GCS_DOCUMENT_FALLBACK_STORAGE_BUCKET: "#{GCS_DOCUMENT_FALLBACK_STORAGE_BUCKET}#"
  GCS_DOCUMENT_STORAGE_BUCKET: "#{GCS_DOCUMENT_STORAGE_BUCKET}#"
  GCS_IMAGE_FALLBACK_STORAGE_BUCKET: "#{GCS_IMAGE_FALLBACK_STORAGE_BUCKET}#"
  GCS_IMAGE_STORAGE_BUCKET: "#{GCS_IMAGE_STORAGE_BUCKET}#"
  GCS_VIDEO_FALLBACK_STORAGE_BUCKET: "#{GCS_VIDEO_FALLBACK_STORAGE_BUCKET}#"
  GCS_VIDEO_STORAGE_BUCKET: "#{GCS_VIDEO_STORAGE_BUCKET}#"
  GOOGLE_APPLICATION_CREDENTIALS: "/var/www/html/var/secure/google/pubsub-credentials.json"
  GOOGLE_BUCKET_CREDENTIALS: "/var/www/html/var/secure/google/storage-bucket-credentials.json"
  GOOGLE_FALLBACK_BUCKET_CREDENTIALS: "/var/www/html/var/secure/google/fallback-storage-bucket-credentials.json"
  IMAGE_ADMIN_CC_TTL: "#{IMAGE_ADMIN_CC_TTL}#"
  IMAGE_ADMIN_MAX_AGE: "#{IMAGE_ADMIN_MAX_AGE}#"
  IMAGE_PUBLIC_CC_TTL: "#{IMAGE_PUBLIC_CC_TTL}#"
  IMAGE_PUBLIC_MAX_AGE: "#{IMAGE_PUBLIC_MAX_AGE}#"
  MESSENGER_ASSET_CHANGE_STATE_TOPIC: "#{MESSENGER_ASSET_CHANGE_STATE_TOPIC}#"
  MESSENGER_ASSET_METADATA_PROCESS_TOPIC: "#{MESSENGER_ASSET_METADATA_PROCESS_TOPIC}#"
  MESSENGER_AUDIO_FILE_CHANGE_STATE_TOPIC: "#{MESSENGER_AUDIO_FILE_CHANGE_STATE_TOPIC}#"
  MESSENGER_DISTRIBUTION_REMOTE_PROCESSED_CHECK_TOPIC: "#{MESSENGER_DISTRIBUTION_REMOTE_PROCESSED_CHECK_TOPIC}#"
  MESSENGER_DISTRIBUTION_TOPIC: "#{MESSENGER_DISTRIBUTION_TOPIC}#"
  MESSENGER_DOCUMENT_FILE_CHANGE_STATE_TOPIC: "#{MESSENGER_DOCUMENT_FILE_CHANGE_STATE_TOPIC}#"
  MESSENGER_IMAGE_FILE_CHANGE_STATE_TOPIC: "#{MESSENGER_IMAGE_FILE_CHANGE_STATE_TOPIC}#"
  MESSENGER_TRANSPORT_DSN: "#{MESSENGER_TRANSPORT_DSN}#"
  MESSENGER_VIDEO_FILE_CHANGE_STATE_TOPIC: "#{MESSENGER_VIDEO_FILE_CHANGE_STATE_TOPIC}#"
  NGINX_ACCESS_LOG: "/var/www/html/var/log/nginx_access.log main"
  NGINX_ALLOWED_ORIGINS_REGEX: "#{NGINX_ALLOWED_ORIGINS_REGEX}#"
  NGINX_CLIENT_BODY_BUFFER_SIZE: "#{NGINX_CLIENT_BODY_BUFFER_SIZE}#"
  NGINX_CLIENT_MAX_BODY_SIZE: "#{NGINX_CLIENT_MAX_BODY_SIZE}#"
  NGINX_ERROR_LOG: "/var/www/html/var/log/nginx_error.log warn"
  NGINX_STATIC_LOCATION_REGEX: "\\.(gif|ico|css|js|svg|bmp|eot|woff|woff2|ttf)$$"
  PHP_ACCESS_LOG: "/var/www/html/var/log/fpm_access.log"
  PHP_ERROR_LOG: "/var/www/html/var/log/fpm_error.log"
  PHP_MEMORY_LIMIT: "#{PHP_MEMORY_LIMIT}#"
  PHP_OPCACHE_PRELOAD_PATH: "/var/www/html/var/cache/prod/App_KernelProdContainer.preload.php"
  PHP_PM_MAX_CHILDREN: "#{PHP_PM_MAX_CHILDREN}#"
  PHP_SLOW_LOG: "/var/www/html/var/log/fpm_error.log"
  PHP_UPLOAD_MAX_FILESIZE: "#{PHP_UPLOAD_MAX_FILESIZE}#"
  PUBLIC_IMAGE_ADMIN_DOMAIN: "#{PUBLIC_IMAGE_ADMIN_DOMAIN}#"
  PUBLIC_IMAGE_DOMAIN: "#{PUBLIC_IMAGE_DOMAIN}#"
  PUBSUB_EMULATOR_HOST: ""
  PURGE_CACHE_XKEY_ENABLED: "#{PURGE_CACHE_XKEY_ENABLED}#"
  PURGE_CDN_ENABLED: "#{PURGE_CDN_ENABLED}#"
  SECURE_CHANNEL: "#{SECURE_CHANNEL}#"
  SSO_CLIENT_ID: "#{SSO_CLIENT_ID}#"
  SSO_PUBLIC_CERT_PATH: "/var/www/html/var/secure/sso/central-oauth2-public-key.pem"
  SSO_USER_INFO_URL: "#{SSO_USER_INFO_URL}#"
---
apiVersion: v1
kind: Secret
metadata:
  name: #{APP_NAME}#
  labels:
    app: #{APP_NAME}#
    type: application
type: Opaque
stringData:
  ANZU_MONGODB_APP_LOG_PASSWORD: "#{ANZU_MONGODB_APP_LOG_PASSWORD}#"
  ANZU_MONGODB_AUDIT_LOG_PASSWORD: "#{ANZU_MONGODB_AUDIT_LOG_PASSWORD}#"
  APP_SECRET: "#{APP_SECRET}#"
  ASSET_EXTERNAL_PROVIDER_UNSPLASH_CMS_ACCESS_KEY: "#{ASSET_EXTERNAL_PROVIDER_UNSPLASH_CMS_ACCESS_KEY}#"
  AUTH_JWT_PRIVATE_CERT: "#{AUTH_JWT_PRIVATE_CERT}#"
  AUTH_OAUTH2_CLIENT_SECRET: "#{AUTH_OAUTH2_CLIENT_SECRET}#"
  DB_ARTEMIS_URL: "mysql://#{DB_CORE_DAM_USER}#:#{DB_CORE_DAM_PASS}#@#{DB_CORE_DAM_HOST}#:#{DB_CORE_DAM_PORT}#/#{DB_ARTEMIS_NAME}#?serverVersion=#{DB_SERVER_VERSION}#"
  DB_BLOG_URL: "mysql://#{DB_CORE_DAM_USER}#:#{DB_CORE_DAM_PASS}#@#{DB_CORE_DAM_HOST}#:#{DB_CORE_DAM_PORT}#/#{DB_BLOG_NAME}#?serverVersion=#{DB_SERVER_VERSION}#"
  DB_CORE_DAM_URL: "mysql://#{DB_CORE_DAM_USER}#:#{DB_CORE_DAM_PASS}#@#{DB_CORE_DAM_HOST}#:#{DB_CORE_DAM_PORT}#/#{DB_CORE_DAM_NAME}#?serverVersion=#{DB_SERVER_VERSION}#"
  DB_CORE_URL: "mysql://#{DB_CORE_DAM_USER}#:#{DB_CORE_DAM_PASS}#@#{DB_CORE_DAM_HOST}#:#{DB_CORE_DAM_PORT}#/#{DB_CORE_NAME}#?serverVersion=#{DB_SERVER_VERSION}#"
  DB_DAM_LEGACY_URL: "mysql://#{DB_CORE_DAM_USER}#:#{DB_CORE_DAM_PASS}#@#{DB_CORE_DAM_HOST}#:#{DB_CORE_DAM_PORT}#/#{DB_DAM_LEGACY_NAME}#?serverVersion=#{DB_SERVER_VERSION}#"
  DISTRIBUTION_ARTEMIS_CMS_API_TOKEN: "#{DISTRIBUTION_ARTEMIS_CMS_API_TOKEN}#"
  DISTRIBUTION_JW_CMS_SECRET_V2: "#{DISTRIBUTION_JW_CMS_SECRET_V2}#"
  YOUTUBE_API_KEY: "#{YOUTUBE_API_KEY}#"
