apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
  labels:
    app: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
    type: application
spec:
  revisionHistoryLimit: 2
  progressDeadlineSeconds: #{DEPLOYMENT_MESSENGER_PROGRESS_DEADLINE_SECONDS}#
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: #{DEPLOYMENT_MESSENGER_ROLLING_UPDATE_MAX_SURGE}#
      maxUnavailable: 0
  selector:
    matchLabels:
      app: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
      type: application
  template:
    metadata:
      labels:
        app: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
        type: application
    spec:
      terminationGracePeriodSeconds: #{DEPLOYMENT_MESSENGER_TERMINATION_GRACE_PERIOD_SECONDS}#
      containers:
        - name: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
          image: petitpress.azurecr.io/#{CRON_DOCKER_IMAGE_REPOSITORY}#:#{VERSION}#
          args: ["start-messenger-command"]
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "pre-stop-messenger-container --messengers"]
          resources:
            limits:
              cpu: #{DEPLOYMENT_MESSENGER_CPU_LIMIT}#
              memory: #{DEPLOYMENT_MESSENGER_MEMORY_LIMIT}#
            requests:
              cpu: #{DEPLOYMENT_MESSENGER_CPU_REQUEST}#
              memory: #{DEPLOYMENT_MESSENGER_MEMORY_REQUEST}#
          envFrom:
            - configMapRef:
                name: #{APP_NAME}#
            - secretRef:
                name: #{APP_NAME}#
          env:
            - name: APP_TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: #{APP_NAME}#-infra
                  key: trusted_ips
            - name: AZURE_DEPLOYMENT_START_TIME
              value: #{SYSTEM_PIPELINESTARTTIME}#
            - name: PHP_MEMORY_LIMIT
              value: "#{APP_PHP_MEMORY_LIMIT}#"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: #{APP_NAME}#-infra
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: #{APP_NAME}#-infra
                  key: redis_port
            - name: REDIS_CACHE_HOST
              valueFrom:
                configMapKeyRef:
                  name: #{APP_NAME}#-infra
                  key: redis_cache_host
            - name: REDIS_CACHE_PORT
              valueFrom:
                configMapKeyRef:
                  name: #{APP_NAME}#-infra
                  key: redis_cache_port
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
            - name: secure-credentials
              mountPath: /var/www/html/var/secure
              readOnly: true
          livenessProbe:
            exec:
              command:
                - cat
                - /var/run/supervisor/supervisord.pid
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
        - name: container-stop-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/container_stop.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-asset-change-state-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_asset_change_state.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-asset-file-metadata-process-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_asset_file_metadata_process.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-audio-file-change-state-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_audio_file_change_state.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-distribution-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_distribution.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-distribution-remote-check-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_distribution_remote_check.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-document-file-change-state-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_document_file_change_state.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-image-file-change-state-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_image_file_change_state.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-media-api-callback-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_media_api_callback.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-media-asset-changed-sync-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_asset_changed_sync.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-property-refresh-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_property_refresh.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-asset-copy-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_asset_copy.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-anzu-core-dam-video-file-change-state-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_anzu_core_dam_video_file_change_state.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
        - name: messenger-core-dam-log-log
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/var/www/html/var/log/tail-cmd -f /var/www/html/var/log/messenger_core_dam_log.log"]
          resources:
            limits:
              cpu: 5m
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 5Mi
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/var/log
      imagePullSecrets:
        - name: acr-regcred
      volumes:
        - name: logs
          emptyDir: {}
        - name: secure-credentials
          secret:
            secretName: #{APP_NAME}#-infra
            items:
              - key: central-oauth2-public-key.pem
                path: sso/central-oauth2-public-key.pem
              - key: central-oauth2-web-public-key.pem
                path: sso/central-oauth2-web-public-key.pem
              - key: dam-general-prod-storage-bucket-credentials.json
                path: google/general-production-storage-bucket-credentials.json
              - key: dam-general-storage-bucket-credentials.json
                path: google/general-storage-bucket-credentials.json
              - key: dam-mediaapi-prod-ro-storage-bucket-credentials.json
                path: google/mediaapi-production-storage-bucket-credentials.json
              - key: dam-mediaapi-ro-storage-bucket-credentials.json
                path: google/mediaapi-storage-bucket-credentials.json
              - key: dam-ro-production-storage-bucket-credentials.json
                path: google/fallback-storage-bucket-credentials.json
              - key: dam-storage-bucket-credentials.json
                path: google/storage-bucket-credentials.json
              - key: dam-youtube-oauth2-credentials.json
                path: youtube/yt_oauth2_credentials.json
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
  labels:
    app: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
    type: application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
  minReplicas: #{HPA_MESSENGER_MIN_REPLICA_COUNT}#
  maxReplicas: #{HPA_MESSENGER_MAX_REPLICA_COUNT}#
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: #{HPA_MESSENGER_AVERAGE_CPU_UTILIZATION}#
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
  labels:
    app: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
    type: application
spec:
  minAvailable: #{PDB_APP_MIN_AVAILABLE}#
  selector:
    matchLabels:
      app: #{MESSENGER_KUBERNETES_DEPLOYMENT_NAME}#
