anzu_systems_core_dam:
    storages:
        cms.audio:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_AUDIO_STORAGE_BUCKET)%'
                prefix: 'audio'
        cms.image:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_IMAGE_STORAGE_BUCKET)%'
                prefix: 'image'
        cms.document:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_DOCUMENT_STORAGE_BUCKET)%'
                prefix: 'document'
        cms.video:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_VIDEO_STORAGE_BUCKET)%'
                prefix: 'video'
        cms.chunk:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_IMAGE_STORAGE_BUCKET)%'
                prefix: 'chunk'
        cms.crop:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_IMAGE_STORAGE_BUCKET)%'
                prefix: 'crop'
