anzu_systems_core_dam:
    storages:
        cms.audio:
            adapter: 'gcloud'
            fallback_enabled: '%env(bool:CMS_AUDIO_FALLBACK_ENABLED)%'
            fallback_storage: cms.audio_fallback
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_AUDIO_STORAGE_BUCKET)%'
                prefix: 'audios'
        cms.public_audio:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_PUBLIC_AUDIO_STORAGE_BUCKET)%'
        cms.image:
            adapter: 'gcloud'
            fallback_enabled: '%env(bool:CMS_IMAGE_FALLBACK_ENABLED)%'
            fallback_storage: cms.image_fallback
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_IMAGE_STORAGE_BUCKET)%'
                prefix: 'assets'
        cms.document:
            adapter: 'gcloud'
            fallback_enabled: '%env(bool:CMS_DOCUMENT_FALLBACK_ENABLED)%'
            fallback_storage: cms.document_fallback
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_DOCUMENT_STORAGE_BUCKET)%'
                prefix: 'documents'
        cms.video:
            adapter: 'gcloud'
            fallback_enabled: '%env(bool:CMS_VIDEO_FALLBACK_ENABLED)%'
            fallback_storage: cms.video_fallback
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_VIDEO_STORAGE_BUCKET)%'
                prefix: 'videos'
        ext.rtmp:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_RTMP_STORAGE_BUCKET)%'
        ext.scraper:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_EXT_SCRAPER_STORAGE_BUCKET)%'
        blog.image:
            adapter: 'gcloud'
            fallback_enabled: '%env(bool:BLOG_IMAGE_FALLBACK_ENABLED)%'
            fallback_storage: blog.image_fallback
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_BLOG_IMAGE_STORAGE_BUCKET)%'
                prefix: 'images'
        cms.chunk:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_IMAGE_STORAGE_BUCKET)%'
                prefix: 'chunk'
        cms.crop:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_IMAGE_STORAGE_BUCKET)%'
                prefix: 'crop'
        blog.crop:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_BLOG_IMAGE_STORAGE_BUCKET)%'
                prefix: 'crop'
        blog.chunk:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_BLOG_IMAGE_STORAGE_BUCKET)%'
                prefix: 'chunk'
        cms.image_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_IMAGE_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'assets'
        blog.image_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_BLOG_IMAGE_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'images'
        cms.audio_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_AUDIO_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'audios'
        cms.video_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_VIDEO_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'videos'
        cms.document_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_DOCUMENT_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'documents'
        scraper.image_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_SCRAPER_IMAGE_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'images'
        scraper.image:
            adapter: 'gcloud'
            fallback_enabled: '%env(bool:SCRAPER_IMAGE_FALLBACK_ENABLED)%'
            fallback_storage: scraper.image_fallback
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_SCRAPER_IMAGE_STORAGE_BUCKET)%'
                prefix: 'images'
        scraper.crop:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_SCRAPER_IMAGE_STORAGE_BUCKET)%'
                prefix: 'crop'
        scraper.chunk:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_SCRAPER_IMAGE_STORAGE_BUCKET)%'
                prefix: 'chunk'
        pressNews.image_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_PRESS_NEWS_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'images'
        pressNews.image:
            adapter: 'gcloud'
            fallback_enabled: '%env(bool:PRESS_NEWS_IMAGE_FALLBACK_ENABLED)%'
            fallback_storage: blog.image_fallback
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_PRESS_NEWS_IMAGE_STORAGE_BUCKET)%'
                prefix: 'images'
        pressNews.crop:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_PRESS_NEWS_IMAGE_STORAGE_BUCKET)%'
                prefix: 'crop'
        pressNews.chunk:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_PRESS_NEWS_IMAGE_STORAGE_BUCKET)%'
                prefix: 'chunk'
        people.image_fallback:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_fallback_client'
                bucket: '%env(string:GCS_PEOPLE_FALLBACK_STORAGE_BUCKET)%'
                prefix: 'images'
        people.image:
            adapter: 'gcloud'
            fallback_enabled: '%env(bool:PEOPLE_IMAGE_FALLBACK_ENABLED)%'
            fallback_storage: people.image_fallback
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_PEOPLE_IMAGE_STORAGE_BUCKET)%'
                prefix: 'images'
        people.crop:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_PEOPLE_IMAGE_STORAGE_BUCKET)%'
                prefix: 'crop'
        people.chunk:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.env_client'
                bucket: '%env(string:GCS_PEOPLE_IMAGE_STORAGE_BUCKET)%'
                prefix: 'chunk'

        general.documents:
            adapter: 'gcloud'
            options:
                client: 'anzu.google_storage.dam_general_prod_client'
                bucket: '%env(string:GCS_GENERAL_DOCUMENT_BUCKET)%'
                prefix: 'public'