### Create file from path
POST {{host}}/api/sys/v1/asset/rtmp
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{haproxySysUserApiToken}}

{
  "path": "deep/test-1686749225.flv"
}

### Create licenced file from path
POST {{host}}/api/sys/v1/asset-file
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{scraperSysUserApiToken}}

{
  "path": "SampleJPGImage_1mbmb.jpg",
  "customData": {
    "providerType": "facebook",
    "originalUrl": "https://www.sme.sk",
    "description": "Cicik",
    "providerId": "raz dva tri",
    "isChild": true,
    "invalidKey": "I am invalid key"
  },
  "generatePublicRoute": true,
  "licence": 101000
}

> {%
    client.global.set('assetFileId', response.body.id);
%}

### Get file
GET {{host}}/api/sys/v1/asset-file/{{assetFileId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{cmsSysUserApiToken}}


### Create licenced file from path
POST {{host}}/api/sys/v1/asset-file/from-url
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{cmsSysUserApiToken}}

{
  "url": "https://m.smedata.sk/api-media/media/image/sme/9/87/8708329/8708329_180x120.jpg?rev=2",
  "customData": {
    "title": "Popis",
    "description": "poopo"
  },
  "authors": [
    "author 3",
    "Teta"
  ],
  "keywords": [
    "keyword 1",
    "keyword 2",
    "Teta v obrazku"
  ],
  "generatePublicRoute": false,
  "licence": 100000
}

> {%
    client.global.set('assetFileId', response.body.id);
%}