### Create image file
POST {{host}}/api/sys/v1/mediaapi/image
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{mediaapiSysUserApiToken}}

// https://m.smedata.sk/api-media/media/image/sme/0/70/7008280/7008280.jpeg
// /sme/0/70/7008280/7008280.jpeg
// https://m.smedata.sk/api-media/media/image/sme/6/22/2255366/2255366_300x200.jpeg
// /sme/6/22/2255366/2255366.jpeg
// https://m.smedata.sk/api-media/media/image/sme/6/31/3129176/3129176.jpeg
// /sme/6/31/3129176/3129176.jpeg
// https://m.smedata.sk/api-media/media/image/sme/3/88/8893563/8893563.jpg

// /sme/0/67/67000030/6700030.jpeg
// /sme/3/88/8893563/8893563.jpg

{
  "mediaApiId": 8893563,
  "fullPath": "/sme/6/22/2255366/2255366.jpeg",
  "idStock": 5,
  "keywords": "",
  "author": "",
  "description": "",
  "focusX": 1500,
  "focusY": 1334,
  "createdAt": "2024-09-30T18:00:14.000000Z",
  "updatedAt": "2024-09-30T18:00:16.000000Z",
  "idCentralUserCreated": 770907,
  "idCentralUserUpdated": 770907,
  "public": true,
  "singleUse": false
}

> {%
    client.global.set('id', response.body.id);
%}

### Delete image file
DELETE {{host}}/api/sys/v1/mediaapi/image/{{id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{mediaapiSysUserApiToken}}


### Create duplicate
POST {{host}}/api/sys/v1/mediaapi/image
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{mediaapiSysUserApiToken}}

// https://m.smedata.sk/api-media/media/image/sme/0/70/7008280/7008280.jpeg
{
  "mediaApiId": 7008282,
  "fullPath": "/sme/6/31/3129176/3129176.jpeg",
  "idStock": 5,
  "author": "Duplicate author",
  "keywords": "duplicate",
  "description": "Duplicate description.",
  "focusX": 1891,
  "focusY": 1309,
  "createdAt": "2024-05-11T00:00:00.000000Z",
  "updatedAt": "2024-05-11T00:00:00.000000Z",
  "idCentralUserCreated": 773001,
  "idCentralUserUpdated": 773001,
  "singleUse": false,
  "public": false
}

> {%
    client.global.set('duplicate_id', response.body.id);
%}

### Update image file
PUT {{host}}/api/sys/v1/mediaapi/image/1ef7fe12-922d-69d8-a07b-bd70646462a4
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{mediaapiSysUserApiToken}}

// https://m.smedata.sk/api-media/media/image/sme/0/70/7008280/7008280.jpeg
{
  "mediaApiId": 8893563,
  "fullPath": "/sme/6/22/2255366/2255366.jpeg",
  "idStock": 5,
  "keywords": "",
  "author": "(DH)",
  "description": "Dominik a jeho rekordný dubák.",
  "focusX": 1500,
  "focusY": 1334,
  "createdAt": "2024-09-30T18:00:14.000000Z",
  "updatedAt": "2024-09-30T18:00:35.000000Z",
  "idCentralUserCreated": 770907,
  "idCentralUserUpdated": 770907,
  "public": true,
  "singleUse": false
}

### Update image file
POST {{host}}/api/sys/v1/image/copy-job
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{cmsSysUserApiToken}}

// https://m.smedata.sk/api-media/media/image/sme/0/70/7008280/7008280.jpeg
{
  "targetAssetLicence": 100001,
  "items": [
    {
      "imageFile": "1f013cc7-d330-647e-8e25-df769310d019"
    }
  ]
}
