<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124134051 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asset (created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, id CHAR(36) NOT NULL, texts_display_title VARCHAR(255) NOT NULL, asset_file_properties_distributes_in_services JSON NOT NULL, asset_file_properties_slot_names JSON NOT NULL, asset_file_properties_from_rss TINYINT(1) NOT NULL, asset_file_properties_width INT UNSIGNED NOT NULL, asset_file_properties_height INT UNSIGNED NOT NULL, dates_uploaded_at DATETIME NOT NULL, dates_expire_at DATETIME DEFAULT NULL, dates_publish_at DATETIME DEFAULT NULL, asset_flags_described TINYINT(1) NOT NULL, asset_flags_visible TINYINT(1) NOT NULL, asset_flags_generated_by_system TINYINT(1) NOT NULL, asset_flags_autocompleted_metadata TINYINT(1) NOT NULL, asset_flags_auto_delete_unprocessed TINYINT(1) NOT NULL, attributes_asset_type VARCHAR(255) NOT NULL, attributes_status VARCHAR(255) NOT NULL, sibling_to_asset_id CHAR(36) DEFAULT NULL, main_file_id CHAR(36) DEFAULT NULL, metadata_id CHAR(36) DEFAULT NULL, licence_id INT DEFAULT NULL, ext_system_id INT DEFAULT NULL, distribution_category_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, notify_to_id INT DEFAULT NULL, INDEX IDX_2AF5A5CCA830096 (sibling_to_asset_id), UNIQUE INDEX UNIQ_2AF5A5C6780D085 (main_file_id), UNIQUE INDEX UNIQ_2AF5A5CDC9EE959 (metadata_id), INDEX IDX_2AF5A5C26EF07C9 (licence_id), INDEX IDX_2AF5A5CE961F7A (ext_system_id), INDEX IDX_2AF5A5C82EDC6B8 (distribution_category_id), INDEX IDX_2AF5A5CB03A8386 (created_by_id), INDEX IDX_2AF5A5C99049ECE (modified_by_id), INDEX IDX_2AF5A5C12433204 (notify_to_id), INDEX IDX_status_created_auto_delete (attributes_status, created_at, asset_flags_auto_delete_unprocessed), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_author (asset_id CHAR(36) NOT NULL, author_id CHAR(36) NOT NULL, INDEX IDX_558257D55DA1941 (asset_id), INDEX IDX_558257D5F675F31B (author_id), PRIMARY KEY (asset_id, author_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_keyword (asset_id CHAR(36) NOT NULL, keyword_id CHAR(36) NOT NULL, INDEX IDX_397D306D5DA1941 (asset_id), INDEX IDX_397D306D115D4552 (keyword_id), PRIMARY KEY (asset_id, keyword_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_file (created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, id CHAR(36) NOT NULL, asset_attributes_checksum VARCHAR(64) NOT NULL, asset_attributes_origin_asset_id VARCHAR(36) NOT NULL, asset_attributes_file_path VARCHAR(255) NOT NULL, asset_attributes_origin_file_name VARCHAR(255) NOT NULL, asset_attributes_mime_type VARCHAR(255) NOT NULL, asset_attributes_convert_to_mime VARCHAR(127) NOT NULL, asset_attributes_size BIGINT NOT NULL, asset_attributes_origin_url VARCHAR(2048) DEFAULT NULL, asset_attributes_origin_external_provider VARCHAR(255) DEFAULT NULL, asset_attributes_origin_storage VARCHAR(255) DEFAULT NULL, asset_attributes_status VARCHAR(255) NOT NULL, asset_attributes_fail_reason VARCHAR(255) NOT NULL, asset_attributes_create_strategy VARCHAR(255) NOT NULL, flags_processed_metadata TINYINT(1) NOT NULL, flags_public TINYINT(1) NOT NULL, flags_single_use TINYINT(1) NOT NULL, metadata_id CHAR(36) DEFAULT NULL, main_route_id CHAR(36) DEFAULT NULL, licence_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, notify_to_id INT DEFAULT NULL, dtype VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_68FBF3D8DC9EE959 (metadata_id), UNIQUE INDEX UNIQ_68FBF3D8EDCEA593 (main_route_id), INDEX IDX_68FBF3D826EF07C9 (licence_id), INDEX IDX_68FBF3D8B03A8386 (created_by_id), INDEX IDX_68FBF3D899049ECE (modified_by_id), INDEX IDX_68FBF3D812433204 (notify_to_id), INDEX IDX_licence_attributes_external_provider (licence_id, asset_attributes_origin_external_provider), INDEX IDX_attributes_status (asset_attributes_status), INDEX IDX_licence_attributes_status_checksum (licence_id, asset_attributes_status, asset_attributes_checksum), INDEX IDX_licence_attributes_status_url (licence_id, asset_attributes_status, asset_attributes_origin_url(255)), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_file_metadata (exif_data JSON NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, id CHAR(36) NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_3D3162E8B03A8386 (created_by_id), INDEX IDX_3D3162E899049ECE (modified_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_file_route (status VARCHAR(255) NOT NULL, mode VARCHAR(255) NOT NULL, id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, uri_path VARCHAR(255) NOT NULL, uri_slug VARCHAR(255) NOT NULL, uri_main TINYINT(1) NOT NULL, target_asset_file_id CHAR(36) NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_6EA67314ECA90B8B (target_asset_file_id), INDEX IDX_6EA67314B03A8386 (created_by_id), INDEX IDX_6EA6731499049ECE (modified_by_id), INDEX IDX_main_asset_file_id (uri_main, target_asset_file_id), UNIQUE INDEX UNIQ_uri_path (uri_path), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_licence (name VARCHAR(255) NOT NULL, ext_id VARCHAR(255) DEFAULT NULL, limited_files TINYINT(1) DEFAULT 0 NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, ext_system_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_7E44A71EE961F7A (ext_system_id), INDEX IDX_7E44A71EB03A8386 (created_by_id), INDEX IDX_7E44A71E99049ECE (modified_by_id), UNIQUE INDEX UNIQ_7E44A71E5E237E06 (name), UNIQUE INDEX UNIQ_7E44A71EE961F7A5D04BFAD (ext_system_id, ext_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_licence_in_group (asset_licence_id INT NOT NULL, asset_licence_group_id INT NOT NULL, INDEX IDX_4C135576E00EE493 (asset_licence_id), INDEX IDX_4C1355769572D68A (asset_licence_group_id), PRIMARY KEY (asset_licence_id, asset_licence_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_licence_group (name VARCHAR(255) NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, ext_system_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_563A0204E961F7A (ext_system_id), INDEX IDX_563A0204B03A8386 (created_by_id), INDEX IDX_563A020499049ECE (modified_by_id), UNIQUE INDEX UNIQ_name_ext_system (name, ext_system_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_metadata (keyword_suggestions JSON NOT NULL, author_suggestions JSON NOT NULL, custom_data JSON NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, id CHAR(36) NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_CD7F2E94B03A8386 (created_by_id), INDEX IDX_CD7F2E9499049ECE (modified_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE asset_slot (name VARCHAR(255) NOT NULL, id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, flags_is_default TINYINT(1) NOT NULL, flags_is_main TINYINT(1) NOT NULL, asset_id CHAR(36) DEFAULT NULL, image_id CHAR(36) DEFAULT NULL, audio_id CHAR(36) DEFAULT NULL, video_id CHAR(36) DEFAULT NULL, document_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_486AE5AF5DA1941 (asset_id), INDEX IDX_486AE5AF3DA5256D (image_id), INDEX IDX_486AE5AF3A3123C7 (audio_id), INDEX IDX_486AE5AF29C1004E (video_id), INDEX IDX_486AE5AFC33F7837 (document_id), INDEX IDX_486AE5AFB03A8386 (created_by_id), INDEX IDX_486AE5AF99049ECE (modified_by_id), INDEX IDX_name (name), INDEX IDX_default (flags_is_default), UNIQUE INDEX UNIQ_asset_file_asset_name (asset_id, name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE audio_file (attributes_duration INT NOT NULL, attributes_codec_name VARCHAR(64) NOT NULL, attributes_bitrate INT NOT NULL, asset_id CHAR(36) DEFAULT NULL, id CHAR(36) NOT NULL, INDEX IDX_C32E2A4C5DA1941 (asset_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE author (name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, flags_can_be_current_author TINYINT(1) DEFAULT 1 NOT NULL, flags_reviewed TINYINT(1) NOT NULL, ext_system_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_BDAFD8C8E961F7A (ext_system_id), INDEX IDX_BDAFD8C8B03A8386 (created_by_id), INDEX IDX_BDAFD8C899049ECE (modified_by_id), UNIQUE INDEX UNIQ_BDAFD8C85E237E06772E836AE961F7A (name, identifier, ext_system_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE author_is_current_author (author_source CHAR(36) NOT NULL, author_target CHAR(36) NOT NULL, INDEX IDX_FE415D6CBA49495E (author_source), INDEX IDX_FE415D6CA3AC19D1 (author_target), PRIMARY KEY (author_source, author_target)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE author_clean_phrase (phrase VARCHAR(255) NOT NULL COLLATE `utf8mb4_bin`, type VARCHAR(255) NOT NULL, mode VARCHAR(255) NOT NULL, id INT UNSIGNED AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, position INT NOT NULL, flags_word_boundary TINYINT(1) DEFAULT 0 NOT NULL, ext_system_id INT DEFAULT NULL, author_replacement_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_5FF642AEE961F7A (ext_system_id), INDEX IDX_5FF642AE43AD0CCA (author_replacement_id), INDEX IDX_5FF642AEB03A8386 (created_by_id), INDEX IDX_5FF642AE99049ECE (modified_by_id), UNIQUE INDEX UNIQ_ext_system_phrase (phrase, ext_system_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE chunk (offset BIGINT NOT NULL, size INT NOT NULL, mime_type VARCHAR(255) NOT NULL, file_path VARCHAR(255) NOT NULL, checksum VARCHAR(64) NOT NULL, id CHAR(36) NOT NULL, asset_file_id CHAR(36) DEFAULT NULL, INDEX IDX_9506712EF025383A (asset_file_id), INDEX IDX_offset (offset), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE custom_form (created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, id CHAR(36) NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, dtype VARCHAR(255) NOT NULL, asset_type VARCHAR(255) DEFAULT NULL, ext_system_id INT DEFAULT NULL, resource_key VARCHAR(255) DEFAULT NULL, INDEX IDX_53FE35B2B03A8386 (created_by_id), INDEX IDX_53FE35B299049ECE (modified_by_id), INDEX IDX_53FE35B2E961F7A (ext_system_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE custom_form_element (name VARCHAR(255) NOT NULL, property VARCHAR(255) NOT NULL, exif_autocomplete JSON NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, id CHAR(36) NOT NULL, position INT NOT NULL, attributes_type VARCHAR(255) NOT NULL, attributes_min_value INT DEFAULT NULL, attributes_max_value INT DEFAULT NULL, attributes_min_count INT DEFAULT NULL, attributes_max_count INT DEFAULT NULL, attributes_required TINYINT(1) NOT NULL, attributes_searchable TINYINT(1) NOT NULL, attributes_readonly TINYINT(1) NOT NULL, form_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_BAB29195FF69B7D (form_id), INDEX IDX_BAB2919B03A8386 (created_by_id), INDEX IDX_BAB291999049ECE (modified_by_id), INDEX IDX_searchable (attributes_searchable), INDEX IDX_position (position), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE distribution (asset_file_id VARCHAR(36) NOT NULL, asset_id VARCHAR(36) NOT NULL, ext_id VARCHAR(512) NOT NULL, distribution_service VARCHAR(128) NOT NULL, status VARCHAR(255) NOT NULL, fail_reason VARCHAR(255) NOT NULL, distribution_data JSON NOT NULL, publish_at DATETIME DEFAULT NULL, id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, distribution_asset_id CHAR(36) DEFAULT NULL, distribution_asset_file_id CHAR(36) DEFAULT NULL, ext_system_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, notify_to_id INT DEFAULT NULL, dtype VARCHAR(255) NOT NULL, privacy VARCHAR(255) DEFAULT NULL, channel_id VARCHAR(32) DEFAULT NULL, playlist VARCHAR(64) DEFAULT NULL, language VARCHAR(20) DEFAULT NULL, texts_title VARCHAR(128) DEFAULT NULL, texts_description VARCHAR(5000) DEFAULT NULL, texts_keywords JSON DEFAULT NULL, flags_embeddable TINYINT(1) DEFAULT NULL, flags_for_kids TINYINT(1) DEFAULT NULL, flags_notify_subscribers TINYINT(1) DEFAULT NULL, direct_source_url VARCHAR(2048) DEFAULT \'\', texts_author VARCHAR(255) DEFAULT NULL, INDEX IDX_A448378120557AAF (distribution_asset_id), INDEX IDX_A44837814CC89533 (distribution_asset_file_id), INDEX IDX_A4483781E961F7A (ext_system_id), INDEX IDX_A4483781B03A8386 (created_by_id), INDEX IDX_A448378199049ECE (modified_by_id), INDEX IDX_A448378112433204 (notify_to_id), INDEX IDX_asset_file_id (asset_file_id), INDEX IDX_asset_id (asset_id), INDEX IDX_asset_file_id_distribution_service (asset_file_id, distribution_service), INDEX IDX_status (status), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE distribution_distribution (distribution_source CHAR(36) NOT NULL, distribution_target CHAR(36) NOT NULL, INDEX IDX_2F6624303B2DD379 (distribution_source), INDEX IDX_2F66243022C883F6 (distribution_target), PRIMARY KEY (distribution_source, distribution_target)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE distribution_category (name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, ext_system_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_23C37A2FE961F7A (ext_system_id), INDEX IDX_23C37A2FB03A8386 (created_by_id), INDEX IDX_23C37A2F99049ECE (modified_by_id), UNIQUE INDEX UNIQ_type_extSystem_name (type, ext_system_id, name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE distribution_category_has_selected_option (distribution_category_id CHAR(36) NOT NULL, distribution_category_option_id CHAR(36) NOT NULL, INDEX IDX_2C4335BB82EDC6B8 (distribution_category_id), INDEX IDX_2C4335BB3BFFCEB1 (distribution_category_option_id), PRIMARY KEY (distribution_category_id, distribution_category_option_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE distribution_category_option (name VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, assignable TINYINT(1) NOT NULL, id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, position INT NOT NULL, select_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_2CCB123ACCDB6D (select_id), INDEX IDX_2CCB123AB03A8386 (created_by_id), INDEX IDX_2CCB123A99049ECE (modified_by_id), UNIQUE INDEX UNIQ_select_name_value (select_id, value), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE distribution_category_select (service_slug VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, ext_system_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_3DBFF84AE961F7A (ext_system_id), INDEX IDX_3DBFF84AB03A8386 (created_by_id), INDEX IDX_3DBFF84A99049ECE (modified_by_id), UNIQUE INDEX UNIQ_extSystem_serviceSlug_type (ext_system_id, service_slug, type), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE document_file (attributes_page_count SMALLINT NOT NULL, asset_id CHAR(36) DEFAULT NULL, id CHAR(36) NOT NULL, INDEX IDX_2B2BBA835DA1941 (asset_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE ext_system (name VARCHAR(255) NOT NULL, slug VARCHAR(32) NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, flags_check_image_used_on_delete TINYINT(1) DEFAULT 0 NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_1A377093B03A8386 (created_by_id), INDEX IDX_1A37709399049ECE (modified_by_id), UNIQUE INDEX UNIQ_slug (slug), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE image_file (image_attributes_ratio_width INT NOT NULL, image_attributes_ratio_height INT NOT NULL, image_attributes_width INT NOT NULL, image_attributes_height INT NOT NULL, image_attributes_rotation SMALLINT NOT NULL, image_attributes_animated TINYINT(1) NOT NULL, image_attributes_most_dominant_color VARCHAR(255) NOT NULL, asset_id CHAR(36) DEFAULT NULL, id CHAR(36) NOT NULL, INDEX IDX_7EA5DC8E5DA1941 (asset_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE image_file_optimal_resize (requested_size INT NOT NULL, width INT NOT NULL, height INT NOT NULL, file_path VARCHAR(255) NOT NULL, original TINYINT(1) NOT NULL, id CHAR(36) NOT NULL, image_id CHAR(36) DEFAULT NULL, INDEX IDX_73F73AAE3DA5256D (image_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE image_preview (position SMALLINT NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, id CHAR(36) NOT NULL, image_file_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_2C9578EC6DB2EB0 (image_file_id), INDEX IDX_2C9578ECB03A8386 (created_by_id), INDEX IDX_2C9578EC99049ECE (modified_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE job (scheduled_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, priority SMALLINT DEFAULT 0 NOT NULL, status VARCHAR(255) NOT NULL, started_at DATETIME DEFAULT NULL, finished_at DATETIME DEFAULT NULL, last_batch_processed_record VARCHAR(2000) NOT NULL, batch_processed_iteration_count INT NOT NULL, result VARCHAR(255) NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, discriminator VARCHAR(255) NOT NULL, INDEX IDX_FBD8E0F8B03A8386 (created_by_id), INDEX IDX_FBD8E0F899049ECE (modified_by_id), INDEX IDX_job (status, scheduled_at, priority), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE job_author_current_optimize (process_all TINYINT(1) DEFAULT 0 NOT NULL, author_id VARCHAR(36) DEFAULT NULL, id INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE job_image_copy (allow_ext_system_callback TINYINT(1) NOT NULL, licence_id INT DEFAULT NULL, id INT NOT NULL, INDEX IDX_D5F7C10126EF07C9 (licence_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE job_image_copy_item (source_asset_id VARCHAR(36) NOT NULL, target_asset_id VARCHAR(36) DEFAULT NULL, status VARCHAR(255) NOT NULL, id INT UNSIGNED AUTO_INCREMENT NOT NULL, job_id INT DEFAULT NULL, INDEX IDX_FD6BA1D9BE04EA9 (job_id), INDEX STATUS_IDX (status), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE job_podcast_synchronizer (podcast_id VARCHAR(36) NOT NULL, full_sync TINYINT(1) NOT NULL, id INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE job_user_data_delete (target_user_id INT NOT NULL, anonymize_user TINYINT(1) NOT NULL, id INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE keyword (name VARCHAR(255) NOT NULL COLLATE `utf8mb4_bin`, id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, flags_reviewed TINYINT(1) NOT NULL, ext_system_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_5A93713BE961F7A (ext_system_id), INDEX IDX_5A93713BB03A8386 (created_by_id), INDEX IDX_5A93713B99049ECE (modified_by_id), UNIQUE INDEX UNIQ_name_extSystem (name, ext_system_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE permission_group (title VARCHAR(255) NOT NULL, description VARCHAR(2000) NOT NULL, permissions JSON NOT NULL, id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_BB4729B62B36786B (title), INDEX IDX_BB4729B6B03A8386 (created_by_id), INDEX IDX_BB4729B699049ECE (modified_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE podcast (id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, texts_title VARCHAR(255) NOT NULL, texts_description VARCHAR(2000) NOT NULL, dates_import_from DATETIME DEFAULT NULL, attributes_rss_url VARCHAR(2048) DEFAULT NULL, attributes_ext_url VARCHAR(2048) DEFAULT \'\' NOT NULL, attributes_file_slot VARCHAR(128) DEFAULT NULL, attributes_last_import_status VARCHAR(255) NOT NULL, attributes_mode VARCHAR(255) NOT NULL, attributes_web_order_position INT UNSIGNED DEFAULT 0 NOT NULL, attributes_mobile_order_position INT UNSIGNED DEFAULT 0 NOT NULL, flags_web_public_export_enabled TINYINT(1) DEFAULT 0 NOT NULL, flags_mobile_public_export_enabled TINYINT(1) DEFAULT 0 NOT NULL, licence_id INT DEFAULT NULL, image_preview_id CHAR(36) DEFAULT NULL, alt_image_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_D7E805BD26EF07C9 (licence_id), UNIQUE INDEX UNIQ_D7E805BDA13A78ED (image_preview_id), UNIQUE INDEX UNIQ_D7E805BD9822B3B6 (alt_image_id), INDEX IDX_D7E805BDB03A8386 (created_by_id), INDEX IDX_D7E805BD99049ECE (modified_by_id), INDEX IDX_name (attributes_mode), INDEX IDX_licence_web_ordering (attributes_web_order_position, licence_id, flags_web_public_export_enabled), INDEX IDX_licence_mobile_ordering (attributes_mobile_order_position, licence_id, flags_mobile_public_export_enabled), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE podcast_episode (id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, position INT NOT NULL, dates_publication_date DATETIME DEFAULT NULL, attributes_rss_url VARCHAR(2048) NOT NULL, attributes_ext_url VARCHAR(2048) DEFAULT \'\' NOT NULL, attributes_rss_id VARCHAR(255) NOT NULL, attributes_last_import_status VARCHAR(255) NOT NULL, attributes_season_number SMALLINT UNSIGNED DEFAULT NULL, attributes_episode_number SMALLINT UNSIGNED DEFAULT NULL, attributes_duration INT UNSIGNED DEFAULT 0 NOT NULL, attributes_web_order_position INT UNSIGNED DEFAULT 0 NOT NULL, attributes_mobile_order_position INT UNSIGNED DEFAULT 0 NOT NULL, flags_from_rss TINYINT(1) NOT NULL, flags_web_public_export_enabled TINYINT(1) DEFAULT 0 NOT NULL, flags_mobile_public_export_enabled TINYINT(1) DEFAULT 0 NOT NULL, texts_title VARCHAR(255) NOT NULL, texts_description LONGTEXT NOT NULL, texts_raw_description LONGTEXT NOT NULL, image_preview_id CHAR(36) DEFAULT NULL, licence_id INT DEFAULT NULL, podcast_id CHAR(36) DEFAULT NULL, asset_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_77EB2BD0A13A78ED (image_preview_id), INDEX IDX_77EB2BD026EF07C9 (licence_id), INDEX IDX_77EB2BD0786136AB (podcast_id), INDEX IDX_77EB2BD05DA1941 (asset_id), INDEX IDX_77EB2BD0B03A8386 (created_by_id), INDEX IDX_77EB2BD099049ECE (modified_by_id), INDEX IDX_podcast_position (podcast_id, position), INDEX IDX_position (position), INDEX IDX_podcast_web_ordering (attributes_web_order_position, asset_id, podcast_id, flags_web_public_export_enabled), INDEX IDX_podcast_mobile_ordering (attributes_mobile_order_position, asset_id, podcast_id, flags_mobile_public_export_enabled), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE public_export (slug VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, id INT UNSIGNED AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, ext_system_id INT DEFAULT NULL, asset_licence_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_427DB92BE961F7A (ext_system_id), INDEX IDX_427DB92BE00EE493 (asset_licence_id), INDEX IDX_427DB92BB03A8386 (created_by_id), INDEX IDX_427DB92B99049ECE (modified_by_id), UNIQUE INDEX UNIQ_slug (slug), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE refresh_token (device_id VARCHAR(36) NOT NULL, token_hash VARCHAR(255) NOT NULL, ip_address VARCHAR(45) NOT NULL, device_info JSON NOT NULL, issued_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, id CHAR(36) NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_C74F2195A76ED395 (user_id), UNIQUE INDEX UNIQ_C74F2195A76ED39594A4C7D4 (user_id, device_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE region_of_interest (point_x INT NOT NULL, point_y INT NOT NULL, percentage_width DOUBLE PRECISION NOT NULL, percentage_height DOUBLE PRECISION NOT NULL, title VARCHAR(128) NOT NULL, id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, position INT NOT NULL, image_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_789D9563DA5256D (image_id), INDEX IDX_789D956B03A8386 (created_by_id), INDEX IDX_789D95699049ECE (modified_by_id), INDEX IDX_position (position), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE user (id INT NOT NULL, email VARCHAR(256) NOT NULL, roles JSON NOT NULL, permissions JSON NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, allowed_asset_external_providers JSON NOT NULL, allowed_distribution_services JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, api_token VARCHAR(255) DEFAULT NULL, person_first_name VARCHAR(120) NOT NULL, person_last_name VARCHAR(120) NOT NULL, person_full_name VARCHAR(242) NOT NULL, avatar_color VARCHAR(7) NOT NULL, avatar_text VARCHAR(3) NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, selected_licence_id INT DEFAULT NULL, INDEX IDX_8D93D649B03A8386 (created_by_id), INDEX IDX_8D93D64999049ECE (modified_by_id), INDEX IDX_8D93D649116F432A (selected_licence_id), UNIQUE INDEX UNIQ_email (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE user_asset_licence (user_id INT NOT NULL, asset_licence_id INT NOT NULL, INDEX IDX_90CA0A4EA76ED395 (user_id), INDEX IDX_90CA0A4EE00EE493 (asset_licence_id), PRIMARY KEY (user_id, asset_licence_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE admins_to_ext_systems (user_id INT NOT NULL, ext_system_id INT NOT NULL, INDEX IDX_C351D3BA76ED395 (user_id), INDEX IDX_C351D3BE961F7A (ext_system_id), PRIMARY KEY (user_id, ext_system_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE user_in_licence_groups (user_id INT NOT NULL, asset_licence_group_id INT NOT NULL, INDEX IDX_1789A906A76ED395 (user_id), INDEX IDX_1789A9069572D68A (asset_licence_group_id), PRIMARY KEY (user_id, asset_licence_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE users_to_ext_systems (user_id INT NOT NULL, ext_system_id INT NOT NULL, INDEX IDX_22399D53A76ED395 (user_id), INDEX IDX_22399D53E961F7A (ext_system_id), PRIMARY KEY (user_id, ext_system_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE user_permission_group (user_id INT NOT NULL, permission_group_id INT NOT NULL, INDEX IDX_C6526B6BA76ED395 (user_id), INDEX IDX_C6526B6BB6C0CF1 (permission_group_id), PRIMARY KEY (user_id, permission_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE video_file (attributes_ratio_width INT NOT NULL, attributes_ratio_height INT NOT NULL, attributes_width INT NOT NULL, attributes_height INT NOT NULL, attributes_rotation SMALLINT NOT NULL, attributes_duration INT NOT NULL, attributes_codec_name VARCHAR(64) NOT NULL, attributes_bitrate INT NOT NULL, image_preview_id CHAR(36) DEFAULT NULL, asset_id CHAR(36) DEFAULT NULL, id CHAR(36) NOT NULL, UNIQUE INDEX UNIQ_8B086BCCA13A78ED (image_preview_id), INDEX IDX_8B086BCC5DA1941 (asset_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE video_show (id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, texts_title VARCHAR(128) NOT NULL, flags_web_public_export_enabled TINYINT(1) DEFAULT 0 NOT NULL, flags_mobile_public_export_enabled TINYINT(1) DEFAULT 0 NOT NULL, attributes_web_order_position INT UNSIGNED DEFAULT 0 NOT NULL, attributes_mobile_order_position INT UNSIGNED DEFAULT 0 NOT NULL, licence_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_359984DD26EF07C9 (licence_id), INDEX IDX_359984DDB03A8386 (created_by_id), INDEX IDX_359984DD99049ECE (modified_by_id), INDEX IDX_name (texts_title), INDEX IDX_licence_web_ordering (attributes_web_order_position, licence_id, flags_web_public_export_enabled), INDEX IDX_licence_mobile_ordering (attributes_mobile_order_position, licence_id, flags_mobile_public_export_enabled), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE video_show_episode (id CHAR(36) NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME NOT NULL, position INT NOT NULL, texts_title VARCHAR(255) NOT NULL, dates_publication_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, flags_web_public_export_enabled TINYINT(1) DEFAULT 0 NOT NULL, flags_mobile_public_export_enabled TINYINT(1) DEFAULT 0 NOT NULL, attributes_web_order_position INT UNSIGNED DEFAULT 0 NOT NULL, attributes_mobile_order_position INT UNSIGNED DEFAULT 0 NOT NULL, video_show_id CHAR(36) DEFAULT NULL, asset_id CHAR(36) DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, INDEX IDX_1B0B20F6352C15C9 (video_show_id), INDEX IDX_1B0B20F65DA1941 (asset_id), INDEX IDX_1B0B20F6B03A8386 (created_by_id), INDEX IDX_1B0B20F699049ECE (modified_by_id), INDEX IDX_video_show_position (video_show_id, position), INDEX IDX_position (position), INDEX IDX_show_publication_mobile_ordering (attributes_mobile_order_position, asset_id, video_show_id, flags_mobile_public_export_enabled, dates_publication_date), INDEX IDX_show_publication_web_ordering (attributes_web_order_position, asset_id, video_show_id, flags_web_public_export_enabled, dates_publication_date), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CCA830096 FOREIGN KEY (sibling_to_asset_id) REFERENCES asset (id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5C6780D085 FOREIGN KEY (main_file_id) REFERENCES asset_file (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CDC9EE959 FOREIGN KEY (metadata_id) REFERENCES asset_metadata (id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5C26EF07C9 FOREIGN KEY (licence_id) REFERENCES asset_licence (id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CE961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5C82EDC6B8 FOREIGN KEY (distribution_category_id) REFERENCES distribution_category (id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5C99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5C12433204 FOREIGN KEY (notify_to_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_author ADD CONSTRAINT FK_558257D55DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE asset_author ADD CONSTRAINT FK_558257D5F675F31B FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE asset_keyword ADD CONSTRAINT FK_397D306D5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE asset_keyword ADD CONSTRAINT FK_397D306D115D4552 FOREIGN KEY (keyword_id) REFERENCES keyword (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE asset_file ADD CONSTRAINT FK_68FBF3D8DC9EE959 FOREIGN KEY (metadata_id) REFERENCES asset_file_metadata (id)');
        $this->addSql('ALTER TABLE asset_file ADD CONSTRAINT FK_68FBF3D8EDCEA593 FOREIGN KEY (main_route_id) REFERENCES asset_file_route (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE asset_file ADD CONSTRAINT FK_68FBF3D826EF07C9 FOREIGN KEY (licence_id) REFERENCES asset_licence (id)');
        $this->addSql('ALTER TABLE asset_file ADD CONSTRAINT FK_68FBF3D8B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_file ADD CONSTRAINT FK_68FBF3D899049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_file ADD CONSTRAINT FK_68FBF3D812433204 FOREIGN KEY (notify_to_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_file_metadata ADD CONSTRAINT FK_3D3162E8B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_file_metadata ADD CONSTRAINT FK_3D3162E899049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_file_route ADD CONSTRAINT FK_6EA67314ECA90B8B FOREIGN KEY (target_asset_file_id) REFERENCES asset_file (id)');
        $this->addSql('ALTER TABLE asset_file_route ADD CONSTRAINT FK_6EA67314B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_file_route ADD CONSTRAINT FK_6EA6731499049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_licence ADD CONSTRAINT FK_7E44A71EE961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE asset_licence ADD CONSTRAINT FK_7E44A71EB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_licence ADD CONSTRAINT FK_7E44A71E99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_licence_in_group ADD CONSTRAINT FK_4C135576E00EE493 FOREIGN KEY (asset_licence_id) REFERENCES asset_licence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE asset_licence_in_group ADD CONSTRAINT FK_4C1355769572D68A FOREIGN KEY (asset_licence_group_id) REFERENCES asset_licence_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE asset_licence_group ADD CONSTRAINT FK_563A0204E961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE asset_licence_group ADD CONSTRAINT FK_563A0204B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_licence_group ADD CONSTRAINT FK_563A020499049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_metadata ADD CONSTRAINT FK_CD7F2E94B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_metadata ADD CONSTRAINT FK_CD7F2E9499049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_slot ADD CONSTRAINT FK_486AE5AF5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id)');
        $this->addSql('ALTER TABLE asset_slot ADD CONSTRAINT FK_486AE5AF3DA5256D FOREIGN KEY (image_id) REFERENCES image_file (id)');
        $this->addSql('ALTER TABLE asset_slot ADD CONSTRAINT FK_486AE5AF3A3123C7 FOREIGN KEY (audio_id) REFERENCES audio_file (id)');
        $this->addSql('ALTER TABLE asset_slot ADD CONSTRAINT FK_486AE5AF29C1004E FOREIGN KEY (video_id) REFERENCES video_file (id)');
        $this->addSql('ALTER TABLE asset_slot ADD CONSTRAINT FK_486AE5AFC33F7837 FOREIGN KEY (document_id) REFERENCES document_file (id)');
        $this->addSql('ALTER TABLE asset_slot ADD CONSTRAINT FK_486AE5AFB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE asset_slot ADD CONSTRAINT FK_486AE5AF99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE audio_file ADD CONSTRAINT FK_C32E2A4C5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE audio_file ADD CONSTRAINT FK_C32E2A4CBF396750 FOREIGN KEY (id) REFERENCES asset_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE author ADD CONSTRAINT FK_BDAFD8C8E961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE author ADD CONSTRAINT FK_BDAFD8C8B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE author ADD CONSTRAINT FK_BDAFD8C899049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE author_is_current_author ADD CONSTRAINT FK_FE415D6CBA49495E FOREIGN KEY (author_source) REFERENCES author (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE author_is_current_author ADD CONSTRAINT FK_FE415D6CA3AC19D1 FOREIGN KEY (author_target) REFERENCES author (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE author_clean_phrase ADD CONSTRAINT FK_5FF642AEE961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE author_clean_phrase ADD CONSTRAINT FK_5FF642AE43AD0CCA FOREIGN KEY (author_replacement_id) REFERENCES author (id)');
        $this->addSql('ALTER TABLE author_clean_phrase ADD CONSTRAINT FK_5FF642AEB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE author_clean_phrase ADD CONSTRAINT FK_5FF642AE99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE chunk ADD CONSTRAINT FK_9506712EF025383A FOREIGN KEY (asset_file_id) REFERENCES asset_file (id)');
        $this->addSql('ALTER TABLE custom_form ADD CONSTRAINT FK_53FE35B2B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE custom_form ADD CONSTRAINT FK_53FE35B299049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE custom_form ADD CONSTRAINT FK_53FE35B2E961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE custom_form_element ADD CONSTRAINT FK_BAB29195FF69B7D FOREIGN KEY (form_id) REFERENCES custom_form (id)');
        $this->addSql('ALTER TABLE custom_form_element ADD CONSTRAINT FK_BAB2919B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE custom_form_element ADD CONSTRAINT FK_BAB291999049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A448378120557AAF FOREIGN KEY (distribution_asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A44837814CC89533 FOREIGN KEY (distribution_asset_file_id) REFERENCES asset_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A4483781E961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A4483781B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A448378199049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A448378112433204 FOREIGN KEY (notify_to_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution_distribution ADD CONSTRAINT FK_2F6624303B2DD379 FOREIGN KEY (distribution_source) REFERENCES distribution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE distribution_distribution ADD CONSTRAINT FK_2F66243022C883F6 FOREIGN KEY (distribution_target) REFERENCES distribution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE distribution_category ADD CONSTRAINT FK_23C37A2FE961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE distribution_category ADD CONSTRAINT FK_23C37A2FB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution_category ADD CONSTRAINT FK_23C37A2F99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution_category_has_selected_option ADD CONSTRAINT FK_2C4335BB82EDC6B8 FOREIGN KEY (distribution_category_id) REFERENCES distribution_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE distribution_category_has_selected_option ADD CONSTRAINT FK_2C4335BB3BFFCEB1 FOREIGN KEY (distribution_category_option_id) REFERENCES distribution_category_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE distribution_category_option ADD CONSTRAINT FK_2CCB123ACCDB6D FOREIGN KEY (select_id) REFERENCES distribution_category_select (id)');
        $this->addSql('ALTER TABLE distribution_category_option ADD CONSTRAINT FK_2CCB123AB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution_category_option ADD CONSTRAINT FK_2CCB123A99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution_category_select ADD CONSTRAINT FK_3DBFF84AE961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE distribution_category_select ADD CONSTRAINT FK_3DBFF84AB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution_category_select ADD CONSTRAINT FK_3DBFF84A99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE document_file ADD CONSTRAINT FK_2B2BBA835DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE document_file ADD CONSTRAINT FK_2B2BBA83BF396750 FOREIGN KEY (id) REFERENCES asset_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ext_system ADD CONSTRAINT FK_1A377093B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ext_system ADD CONSTRAINT FK_1A37709399049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE image_file ADD CONSTRAINT FK_7EA5DC8E5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE image_file ADD CONSTRAINT FK_7EA5DC8EBF396750 FOREIGN KEY (id) REFERENCES asset_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE image_file_optimal_resize ADD CONSTRAINT FK_73F73AAE3DA5256D FOREIGN KEY (image_id) REFERENCES image_file (id)');
        $this->addSql('ALTER TABLE image_preview ADD CONSTRAINT FK_2C9578EC6DB2EB0 FOREIGN KEY (image_file_id) REFERENCES image_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE image_preview ADD CONSTRAINT FK_2C9578ECB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE image_preview ADD CONSTRAINT FK_2C9578EC99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F8B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F899049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job_author_current_optimize ADD CONSTRAINT FK_B33B2963BF396750 FOREIGN KEY (id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_image_copy ADD CONSTRAINT FK_D5F7C10126EF07C9 FOREIGN KEY (licence_id) REFERENCES asset_licence (id)');
        $this->addSql('ALTER TABLE job_image_copy ADD CONSTRAINT FK_D5F7C101BF396750 FOREIGN KEY (id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_image_copy_item ADD CONSTRAINT FK_FD6BA1D9BE04EA9 FOREIGN KEY (job_id) REFERENCES job_image_copy (id)');
        $this->addSql('ALTER TABLE job_podcast_synchronizer ADD CONSTRAINT FK_8A540C84BF396750 FOREIGN KEY (id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_user_data_delete ADD CONSTRAINT FK_2E11648DBF396750 FOREIGN KEY (id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE keyword ADD CONSTRAINT FK_5A93713BE961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE keyword ADD CONSTRAINT FK_5A93713BB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE keyword ADD CONSTRAINT FK_5A93713B99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE permission_group ADD CONSTRAINT FK_BB4729B6B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE permission_group ADD CONSTRAINT FK_BB4729B699049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE podcast ADD CONSTRAINT FK_D7E805BD26EF07C9 FOREIGN KEY (licence_id) REFERENCES asset_licence (id)');
        $this->addSql('ALTER TABLE podcast ADD CONSTRAINT FK_D7E805BDA13A78ED FOREIGN KEY (image_preview_id) REFERENCES image_preview (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE podcast ADD CONSTRAINT FK_D7E805BD9822B3B6 FOREIGN KEY (alt_image_id) REFERENCES image_preview (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE podcast ADD CONSTRAINT FK_D7E805BDB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE podcast ADD CONSTRAINT FK_D7E805BD99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE podcast_episode ADD CONSTRAINT FK_77EB2BD0A13A78ED FOREIGN KEY (image_preview_id) REFERENCES image_preview (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE podcast_episode ADD CONSTRAINT FK_77EB2BD026EF07C9 FOREIGN KEY (licence_id) REFERENCES asset_licence (id)');
        $this->addSql('ALTER TABLE podcast_episode ADD CONSTRAINT FK_77EB2BD0786136AB FOREIGN KEY (podcast_id) REFERENCES podcast (id)');
        $this->addSql('ALTER TABLE podcast_episode ADD CONSTRAINT FK_77EB2BD05DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id)');
        $this->addSql('ALTER TABLE podcast_episode ADD CONSTRAINT FK_77EB2BD0B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE podcast_episode ADD CONSTRAINT FK_77EB2BD099049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE public_export ADD CONSTRAINT FK_427DB92BE961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id)');
        $this->addSql('ALTER TABLE public_export ADD CONSTRAINT FK_427DB92BE00EE493 FOREIGN KEY (asset_licence_id) REFERENCES asset_licence (id)');
        $this->addSql('ALTER TABLE public_export ADD CONSTRAINT FK_427DB92BB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE public_export ADD CONSTRAINT FK_427DB92B99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F2195A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE region_of_interest ADD CONSTRAINT FK_789D9563DA5256D FOREIGN KEY (image_id) REFERENCES image_file (id)');
        $this->addSql('ALTER TABLE region_of_interest ADD CONSTRAINT FK_789D956B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE region_of_interest ADD CONSTRAINT FK_789D95699049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64999049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649116F432A FOREIGN KEY (selected_licence_id) REFERENCES asset_licence (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_asset_licence ADD CONSTRAINT FK_90CA0A4EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_asset_licence ADD CONSTRAINT FK_90CA0A4EE00EE493 FOREIGN KEY (asset_licence_id) REFERENCES asset_licence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE admins_to_ext_systems ADD CONSTRAINT FK_C351D3BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE admins_to_ext_systems ADD CONSTRAINT FK_C351D3BE961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_in_licence_groups ADD CONSTRAINT FK_1789A906A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_in_licence_groups ADD CONSTRAINT FK_1789A9069572D68A FOREIGN KEY (asset_licence_group_id) REFERENCES asset_licence_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE users_to_ext_systems ADD CONSTRAINT FK_22399D53A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE users_to_ext_systems ADD CONSTRAINT FK_22399D53E961F7A FOREIGN KEY (ext_system_id) REFERENCES ext_system (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_permission_group ADD CONSTRAINT FK_C6526B6BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_permission_group ADD CONSTRAINT FK_C6526B6BB6C0CF1 FOREIGN KEY (permission_group_id) REFERENCES permission_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_file ADD CONSTRAINT FK_8B086BCCA13A78ED FOREIGN KEY (image_preview_id) REFERENCES image_preview (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE video_file ADD CONSTRAINT FK_8B086BCC5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE video_file ADD CONSTRAINT FK_8B086BCCBF396750 FOREIGN KEY (id) REFERENCES asset_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_show ADD CONSTRAINT FK_359984DD26EF07C9 FOREIGN KEY (licence_id) REFERENCES asset_licence (id)');
        $this->addSql('ALTER TABLE video_show ADD CONSTRAINT FK_359984DDB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE video_show ADD CONSTRAINT FK_359984DD99049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE video_show_episode ADD CONSTRAINT FK_1B0B20F6352C15C9 FOREIGN KEY (video_show_id) REFERENCES video_show (id)');
        $this->addSql('ALTER TABLE video_show_episode ADD CONSTRAINT FK_1B0B20F65DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id)');
        $this->addSql('ALTER TABLE video_show_episode ADD CONSTRAINT FK_1B0B20F6B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE video_show_episode ADD CONSTRAINT FK_1B0B20F699049ECE FOREIGN KEY (modified_by_id) REFERENCES user (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5CCA830096');
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5C6780D085');
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5CDC9EE959');
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5C26EF07C9');
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5CE961F7A');
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5C82EDC6B8');
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5CB03A8386');
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5C99049ECE');
        $this->addSql('ALTER TABLE asset DROP FOREIGN KEY FK_2AF5A5C12433204');
        $this->addSql('ALTER TABLE asset_author DROP FOREIGN KEY FK_558257D55DA1941');
        $this->addSql('ALTER TABLE asset_author DROP FOREIGN KEY FK_558257D5F675F31B');
        $this->addSql('ALTER TABLE asset_keyword DROP FOREIGN KEY FK_397D306D5DA1941');
        $this->addSql('ALTER TABLE asset_keyword DROP FOREIGN KEY FK_397D306D115D4552');
        $this->addSql('ALTER TABLE asset_file DROP FOREIGN KEY FK_68FBF3D8DC9EE959');
        $this->addSql('ALTER TABLE asset_file DROP FOREIGN KEY FK_68FBF3D8EDCEA593');
        $this->addSql('ALTER TABLE asset_file DROP FOREIGN KEY FK_68FBF3D826EF07C9');
        $this->addSql('ALTER TABLE asset_file DROP FOREIGN KEY FK_68FBF3D8B03A8386');
        $this->addSql('ALTER TABLE asset_file DROP FOREIGN KEY FK_68FBF3D899049ECE');
        $this->addSql('ALTER TABLE asset_file DROP FOREIGN KEY FK_68FBF3D812433204');
        $this->addSql('ALTER TABLE asset_file_metadata DROP FOREIGN KEY FK_3D3162E8B03A8386');
        $this->addSql('ALTER TABLE asset_file_metadata DROP FOREIGN KEY FK_3D3162E899049ECE');
        $this->addSql('ALTER TABLE asset_file_route DROP FOREIGN KEY FK_6EA67314ECA90B8B');
        $this->addSql('ALTER TABLE asset_file_route DROP FOREIGN KEY FK_6EA67314B03A8386');
        $this->addSql('ALTER TABLE asset_file_route DROP FOREIGN KEY FK_6EA6731499049ECE');
        $this->addSql('ALTER TABLE asset_licence DROP FOREIGN KEY FK_7E44A71EE961F7A');
        $this->addSql('ALTER TABLE asset_licence DROP FOREIGN KEY FK_7E44A71EB03A8386');
        $this->addSql('ALTER TABLE asset_licence DROP FOREIGN KEY FK_7E44A71E99049ECE');
        $this->addSql('ALTER TABLE asset_licence_in_group DROP FOREIGN KEY FK_4C135576E00EE493');
        $this->addSql('ALTER TABLE asset_licence_in_group DROP FOREIGN KEY FK_4C1355769572D68A');
        $this->addSql('ALTER TABLE asset_licence_group DROP FOREIGN KEY FK_563A0204E961F7A');
        $this->addSql('ALTER TABLE asset_licence_group DROP FOREIGN KEY FK_563A0204B03A8386');
        $this->addSql('ALTER TABLE asset_licence_group DROP FOREIGN KEY FK_563A020499049ECE');
        $this->addSql('ALTER TABLE asset_metadata DROP FOREIGN KEY FK_CD7F2E94B03A8386');
        $this->addSql('ALTER TABLE asset_metadata DROP FOREIGN KEY FK_CD7F2E9499049ECE');
        $this->addSql('ALTER TABLE asset_slot DROP FOREIGN KEY FK_486AE5AF5DA1941');
        $this->addSql('ALTER TABLE asset_slot DROP FOREIGN KEY FK_486AE5AF3DA5256D');
        $this->addSql('ALTER TABLE asset_slot DROP FOREIGN KEY FK_486AE5AF3A3123C7');
        $this->addSql('ALTER TABLE asset_slot DROP FOREIGN KEY FK_486AE5AF29C1004E');
        $this->addSql('ALTER TABLE asset_slot DROP FOREIGN KEY FK_486AE5AFC33F7837');
        $this->addSql('ALTER TABLE asset_slot DROP FOREIGN KEY FK_486AE5AFB03A8386');
        $this->addSql('ALTER TABLE asset_slot DROP FOREIGN KEY FK_486AE5AF99049ECE');
        $this->addSql('ALTER TABLE audio_file DROP FOREIGN KEY FK_C32E2A4C5DA1941');
        $this->addSql('ALTER TABLE audio_file DROP FOREIGN KEY FK_C32E2A4CBF396750');
        $this->addSql('ALTER TABLE author DROP FOREIGN KEY FK_BDAFD8C8E961F7A');
        $this->addSql('ALTER TABLE author DROP FOREIGN KEY FK_BDAFD8C8B03A8386');
        $this->addSql('ALTER TABLE author DROP FOREIGN KEY FK_BDAFD8C899049ECE');
        $this->addSql('ALTER TABLE author_is_current_author DROP FOREIGN KEY FK_FE415D6CBA49495E');
        $this->addSql('ALTER TABLE author_is_current_author DROP FOREIGN KEY FK_FE415D6CA3AC19D1');
        $this->addSql('ALTER TABLE author_clean_phrase DROP FOREIGN KEY FK_5FF642AEE961F7A');
        $this->addSql('ALTER TABLE author_clean_phrase DROP FOREIGN KEY FK_5FF642AE43AD0CCA');
        $this->addSql('ALTER TABLE author_clean_phrase DROP FOREIGN KEY FK_5FF642AEB03A8386');
        $this->addSql('ALTER TABLE author_clean_phrase DROP FOREIGN KEY FK_5FF642AE99049ECE');
        $this->addSql('ALTER TABLE chunk DROP FOREIGN KEY FK_9506712EF025383A');
        $this->addSql('ALTER TABLE custom_form DROP FOREIGN KEY FK_53FE35B2B03A8386');
        $this->addSql('ALTER TABLE custom_form DROP FOREIGN KEY FK_53FE35B299049ECE');
        $this->addSql('ALTER TABLE custom_form DROP FOREIGN KEY FK_53FE35B2E961F7A');
        $this->addSql('ALTER TABLE custom_form_element DROP FOREIGN KEY FK_BAB29195FF69B7D');
        $this->addSql('ALTER TABLE custom_form_element DROP FOREIGN KEY FK_BAB2919B03A8386');
        $this->addSql('ALTER TABLE custom_form_element DROP FOREIGN KEY FK_BAB291999049ECE');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A448378120557AAF');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A44837814CC89533');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A4483781E961F7A');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A4483781B03A8386');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A448378199049ECE');
        $this->addSql('ALTER TABLE distribution DROP FOREIGN KEY FK_A448378112433204');
        $this->addSql('ALTER TABLE distribution_distribution DROP FOREIGN KEY FK_2F6624303B2DD379');
        $this->addSql('ALTER TABLE distribution_distribution DROP FOREIGN KEY FK_2F66243022C883F6');
        $this->addSql('ALTER TABLE distribution_category DROP FOREIGN KEY FK_23C37A2FE961F7A');
        $this->addSql('ALTER TABLE distribution_category DROP FOREIGN KEY FK_23C37A2FB03A8386');
        $this->addSql('ALTER TABLE distribution_category DROP FOREIGN KEY FK_23C37A2F99049ECE');
        $this->addSql('ALTER TABLE distribution_category_has_selected_option DROP FOREIGN KEY FK_2C4335BB82EDC6B8');
        $this->addSql('ALTER TABLE distribution_category_has_selected_option DROP FOREIGN KEY FK_2C4335BB3BFFCEB1');
        $this->addSql('ALTER TABLE distribution_category_option DROP FOREIGN KEY FK_2CCB123ACCDB6D');
        $this->addSql('ALTER TABLE distribution_category_option DROP FOREIGN KEY FK_2CCB123AB03A8386');
        $this->addSql('ALTER TABLE distribution_category_option DROP FOREIGN KEY FK_2CCB123A99049ECE');
        $this->addSql('ALTER TABLE distribution_category_select DROP FOREIGN KEY FK_3DBFF84AE961F7A');
        $this->addSql('ALTER TABLE distribution_category_select DROP FOREIGN KEY FK_3DBFF84AB03A8386');
        $this->addSql('ALTER TABLE distribution_category_select DROP FOREIGN KEY FK_3DBFF84A99049ECE');
        $this->addSql('ALTER TABLE document_file DROP FOREIGN KEY FK_2B2BBA835DA1941');
        $this->addSql('ALTER TABLE document_file DROP FOREIGN KEY FK_2B2BBA83BF396750');
        $this->addSql('ALTER TABLE ext_system DROP FOREIGN KEY FK_1A377093B03A8386');
        $this->addSql('ALTER TABLE ext_system DROP FOREIGN KEY FK_1A37709399049ECE');
        $this->addSql('ALTER TABLE image_file DROP FOREIGN KEY FK_7EA5DC8E5DA1941');
        $this->addSql('ALTER TABLE image_file DROP FOREIGN KEY FK_7EA5DC8EBF396750');
        $this->addSql('ALTER TABLE image_file_optimal_resize DROP FOREIGN KEY FK_73F73AAE3DA5256D');
        $this->addSql('ALTER TABLE image_preview DROP FOREIGN KEY FK_2C9578EC6DB2EB0');
        $this->addSql('ALTER TABLE image_preview DROP FOREIGN KEY FK_2C9578ECB03A8386');
        $this->addSql('ALTER TABLE image_preview DROP FOREIGN KEY FK_2C9578EC99049ECE');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F8B03A8386');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F899049ECE');
        $this->addSql('ALTER TABLE job_author_current_optimize DROP FOREIGN KEY FK_B33B2963BF396750');
        $this->addSql('ALTER TABLE job_image_copy DROP FOREIGN KEY FK_D5F7C10126EF07C9');
        $this->addSql('ALTER TABLE job_image_copy DROP FOREIGN KEY FK_D5F7C101BF396750');
        $this->addSql('ALTER TABLE job_image_copy_item DROP FOREIGN KEY FK_FD6BA1D9BE04EA9');
        $this->addSql('ALTER TABLE job_podcast_synchronizer DROP FOREIGN KEY FK_8A540C84BF396750');
        $this->addSql('ALTER TABLE job_user_data_delete DROP FOREIGN KEY FK_2E11648DBF396750');
        $this->addSql('ALTER TABLE keyword DROP FOREIGN KEY FK_5A93713BE961F7A');
        $this->addSql('ALTER TABLE keyword DROP FOREIGN KEY FK_5A93713BB03A8386');
        $this->addSql('ALTER TABLE keyword DROP FOREIGN KEY FK_5A93713B99049ECE');
        $this->addSql('ALTER TABLE permission_group DROP FOREIGN KEY FK_BB4729B6B03A8386');
        $this->addSql('ALTER TABLE permission_group DROP FOREIGN KEY FK_BB4729B699049ECE');
        $this->addSql('ALTER TABLE podcast DROP FOREIGN KEY FK_D7E805BD26EF07C9');
        $this->addSql('ALTER TABLE podcast DROP FOREIGN KEY FK_D7E805BDA13A78ED');
        $this->addSql('ALTER TABLE podcast DROP FOREIGN KEY FK_D7E805BD9822B3B6');
        $this->addSql('ALTER TABLE podcast DROP FOREIGN KEY FK_D7E805BDB03A8386');
        $this->addSql('ALTER TABLE podcast DROP FOREIGN KEY FK_D7E805BD99049ECE');
        $this->addSql('ALTER TABLE podcast_episode DROP FOREIGN KEY FK_77EB2BD0A13A78ED');
        $this->addSql('ALTER TABLE podcast_episode DROP FOREIGN KEY FK_77EB2BD026EF07C9');
        $this->addSql('ALTER TABLE podcast_episode DROP FOREIGN KEY FK_77EB2BD0786136AB');
        $this->addSql('ALTER TABLE podcast_episode DROP FOREIGN KEY FK_77EB2BD05DA1941');
        $this->addSql('ALTER TABLE podcast_episode DROP FOREIGN KEY FK_77EB2BD0B03A8386');
        $this->addSql('ALTER TABLE podcast_episode DROP FOREIGN KEY FK_77EB2BD099049ECE');
        $this->addSql('ALTER TABLE public_export DROP FOREIGN KEY FK_427DB92BE961F7A');
        $this->addSql('ALTER TABLE public_export DROP FOREIGN KEY FK_427DB92BE00EE493');
        $this->addSql('ALTER TABLE public_export DROP FOREIGN KEY FK_427DB92BB03A8386');
        $this->addSql('ALTER TABLE public_export DROP FOREIGN KEY FK_427DB92B99049ECE');
        $this->addSql('ALTER TABLE refresh_token DROP FOREIGN KEY FK_C74F2195A76ED395');
        $this->addSql('ALTER TABLE region_of_interest DROP FOREIGN KEY FK_789D9563DA5256D');
        $this->addSql('ALTER TABLE region_of_interest DROP FOREIGN KEY FK_789D956B03A8386');
        $this->addSql('ALTER TABLE region_of_interest DROP FOREIGN KEY FK_789D95699049ECE');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649B03A8386');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64999049ECE');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649116F432A');
        $this->addSql('ALTER TABLE user_asset_licence DROP FOREIGN KEY FK_90CA0A4EA76ED395');
        $this->addSql('ALTER TABLE user_asset_licence DROP FOREIGN KEY FK_90CA0A4EE00EE493');
        $this->addSql('ALTER TABLE admins_to_ext_systems DROP FOREIGN KEY FK_C351D3BA76ED395');
        $this->addSql('ALTER TABLE admins_to_ext_systems DROP FOREIGN KEY FK_C351D3BE961F7A');
        $this->addSql('ALTER TABLE user_in_licence_groups DROP FOREIGN KEY FK_1789A906A76ED395');
        $this->addSql('ALTER TABLE user_in_licence_groups DROP FOREIGN KEY FK_1789A9069572D68A');
        $this->addSql('ALTER TABLE users_to_ext_systems DROP FOREIGN KEY FK_22399D53A76ED395');
        $this->addSql('ALTER TABLE users_to_ext_systems DROP FOREIGN KEY FK_22399D53E961F7A');
        $this->addSql('ALTER TABLE user_permission_group DROP FOREIGN KEY FK_C6526B6BA76ED395');
        $this->addSql('ALTER TABLE user_permission_group DROP FOREIGN KEY FK_C6526B6BB6C0CF1');
        $this->addSql('ALTER TABLE video_file DROP FOREIGN KEY FK_8B086BCCA13A78ED');
        $this->addSql('ALTER TABLE video_file DROP FOREIGN KEY FK_8B086BCC5DA1941');
        $this->addSql('ALTER TABLE video_file DROP FOREIGN KEY FK_8B086BCCBF396750');
        $this->addSql('ALTER TABLE video_show DROP FOREIGN KEY FK_359984DD26EF07C9');
        $this->addSql('ALTER TABLE video_show DROP FOREIGN KEY FK_359984DDB03A8386');
        $this->addSql('ALTER TABLE video_show DROP FOREIGN KEY FK_359984DD99049ECE');
        $this->addSql('ALTER TABLE video_show_episode DROP FOREIGN KEY FK_1B0B20F6352C15C9');
        $this->addSql('ALTER TABLE video_show_episode DROP FOREIGN KEY FK_1B0B20F65DA1941');
        $this->addSql('ALTER TABLE video_show_episode DROP FOREIGN KEY FK_1B0B20F6B03A8386');
        $this->addSql('ALTER TABLE video_show_episode DROP FOREIGN KEY FK_1B0B20F699049ECE');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE asset_author');
        $this->addSql('DROP TABLE asset_keyword');
        $this->addSql('DROP TABLE asset_file');
        $this->addSql('DROP TABLE asset_file_metadata');
        $this->addSql('DROP TABLE asset_file_route');
        $this->addSql('DROP TABLE asset_licence');
        $this->addSql('DROP TABLE asset_licence_in_group');
        $this->addSql('DROP TABLE asset_licence_group');
        $this->addSql('DROP TABLE asset_metadata');
        $this->addSql('DROP TABLE asset_slot');
        $this->addSql('DROP TABLE audio_file');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE author_is_current_author');
        $this->addSql('DROP TABLE author_clean_phrase');
        $this->addSql('DROP TABLE chunk');
        $this->addSql('DROP TABLE custom_form');
        $this->addSql('DROP TABLE custom_form_element');
        $this->addSql('DROP TABLE distribution');
        $this->addSql('DROP TABLE distribution_distribution');
        $this->addSql('DROP TABLE distribution_category');
        $this->addSql('DROP TABLE distribution_category_has_selected_option');
        $this->addSql('DROP TABLE distribution_category_option');
        $this->addSql('DROP TABLE distribution_category_select');
        $this->addSql('DROP TABLE document_file');
        $this->addSql('DROP TABLE ext_system');
        $this->addSql('DROP TABLE image_file');
        $this->addSql('DROP TABLE image_file_optimal_resize');
        $this->addSql('DROP TABLE image_preview');
        $this->addSql('DROP TABLE job');
        $this->addSql('DROP TABLE job_author_current_optimize');
        $this->addSql('DROP TABLE job_image_copy');
        $this->addSql('DROP TABLE job_image_copy_item');
        $this->addSql('DROP TABLE job_podcast_synchronizer');
        $this->addSql('DROP TABLE job_user_data_delete');
        $this->addSql('DROP TABLE keyword');
        $this->addSql('DROP TABLE permission_group');
        $this->addSql('DROP TABLE podcast');
        $this->addSql('DROP TABLE podcast_episode');
        $this->addSql('DROP TABLE public_export');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE region_of_interest');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_asset_licence');
        $this->addSql('DROP TABLE admins_to_ext_systems');
        $this->addSql('DROP TABLE user_in_licence_groups');
        $this->addSql('DROP TABLE users_to_ext_systems');
        $this->addSql('DROP TABLE user_permission_group');
        $this->addSql('DROP TABLE video_file');
        $this->addSql('DROP TABLE video_show');
        $this->addSql('DROP TABLE video_show_episode');
    }
}
